### ISSUE TITLE
FreeSWITCH doesn't restart after GemeinschaftSetup#create

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#101]
Rails raises the following error, when I activate this code:
https://github.com/amooma/GS5/blob/develop/app/controllers/gemeinschaft_setups_controller.rb#L49-L51

![Bildschirmfoto 2013-01-15 um 19 22 13](https://f.cloud.github.com/assets/69770/68717/9c90a342-5f40-11e2-9bd5-53079290a14d.png)

@spag Is anything missing there?

**Comment by jpawlowski** [comment]
For me it worked yesterday with a fresh installation of the dev build.

**Comment by wintermeyer** [comment]
Could it be a problem that I don't have a running FreeSWITCH on my Rails development system? If yes: Is there a way to not raise an error in that case?
