### ISSUE TITLE
Truncate values in gs_paramters grid view

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#103]
To avoid such overlapping grid views the full value should only be shown in the detailed view.
![Screen Shot 2013-01-15 at 21 01 33](https://f.cloud.github.com/assets/75446/69092/84ab395a-5f4e-11e2-8077-72d271ea0278.png)

**Comment by wintermeyer** [comment]
Fixed by ca77ad70f4c2df28f6460e0160f23d115174440d
