### ISSUE TITLE
Allow to see all user groups of a tenant

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#105]
related to #104 , please also allow to see all custom groups. at the moment new groups won't show up here and I need to go to /tenants/2/user_groups manually.

**Comment by wintermeyer** [comment]
One could argue that a list of users should be displayed too.

**Comment by jpawlowski** [comment]
It's more that it's hard to understand that although I'm allowed to create new groups here I cannot see all existing ones.
That's why I requested adding the complete user list more prominently to the tentants page.
To be honest, the whole concept became clear for me only a few hours ago because of these tickets. It's confusing for me as an admin to do admin tasks in my own profile as well as in the tenant area.
