### ISSUE TITLE
Demo-mode status should be mentioned somewhere on each page

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#11]
If we are running in Demo Live-Mode users should see this also in the web gui.
This information can be extracted quite easily, this is something in Shell script you could adapt to ruby code:

```
if [[ x`cat /proc/cmdline | grep boot=live` != x"" ]]
    then
    LIVE=true
else
    LIVE=false
fi
```

**Comment by wintermeyer** [comment]
Got cold feet. It is not important enough for adding a potential problem on OSes we don't know.

**Comment by jpawlowski** [comment]
Something I can't really understand... which potential problem?!? which OS we don't know?

"YOU ARE IN LIVE MODE, CHANGES WILL BE LOST AFTER REBOOT" is worth mentioning in the web interface too, not only on the login prompt.

**Comment by wintermeyer** [comment]
There is bigger fish to try.
