### ISSUE TITLE
Whitelist for dummy account emergency numbers.

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#110]
In Germany we have to whiteliste the following numbers:

Roteskreuz:       116117
Polizei:                 110
Feuerwehr:       112
Behördenhotline: 115
Empfang Köln:            022191610
ServiceDesk:     08001541111 und 02219161 1111 und 601111

**Comment by wintermeyer** [comment]
@spag Any idea on this? A new model or can we use existing stuff?

**Comment by wintermeyer** [comment]
@spag Could we create a phone_book with these numbers which acts as a whitelist?

**Comment by spag** [comment]
@wintermeyer What do you need this whitelist for?

If it's simply for routing purposes then why not create a route then?
The GS5 routing engine is a mysterious and powerful device and its mystery is only exceeded by its power.

**Comment by wintermeyer** [comment]
Some of the GS5 users want to be able to make a 911 call from ANY phone. Even if it's a phone which hasn't been logged in by a user. Can we solve this with the routing engine?

**Comment by spag** [comment]
Yes. That's the primary task of a call router.
The GS5 router is a mysterious and powerful device and its mystery is only exceeded by its power.

**Comment by spag** [comment]
As this seems to be solely a configuration issue - should we close this ticket?
