### ISSUE TITLE
Caching: Wrong link to create tenant phone

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#112]
![Screen Shot 2013-01-18 at 10 16 10](https://f.cloud.github.com/assets/75446/77626/d9fe3562-614f-11e2-8f6d-efc6bef6065b.png)

**Comment by wintermeyer** [comment]
Is this a fresh or an old installation? It seems to be an old cache.

**Comment by jpawlowski** [comment]
a very fresh one ;-)

**Comment by jpawlowski** [comment]
I just did a `gs-update.sh --factory-reset` which completely deletes /opt/GS5 and recreates everything from scratch. Issue persists...

**Comment by wintermeyer** [comment]
Did you restart memcached?

**Comment by jpawlowski** [comment]
Yes, factory-reset does a restart of the complete system to ensure this.
