### ISSUE TITLE
gs_parameters cannot be edited via GUI

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#113]
Clicking on "edit" for a setting in /gs_parameter leads to the following error:
`Required parameter missing: gs_parameter`

**Comment by wintermeyer** [comment]
Fixed by dc3f3ef

**Comment by jpawlowski** [comment]
Now it seems links to "View" and "Edit" are missing

**Comment by wintermeyer** [comment]
I can't replicate this error but did fix other stuff in the meantime. So maybe it was a side effect.

**Comment by jpawlowski** [comment]
hm it's gone here also now, lets close this issue again for now.
