### ISSUE TITLE
Caching issue with version number

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#116]
After playing around with some back and forth updates the GS5 caching seems to be confused about changed versions.
At first it showed only the old version 5.0.2, after refreshing the browser window it shows the version as in the attached screenshot
![Screen Shot 2013-01-19 at 19 45 37](https://f.cloud.github.com/assets/75446/80526/e565d378-6268-11e2-8a32-1f37b5469ee9.png)

**Comment by wintermeyer** [comment]
Fresh install or updated with the script?

**Comment by jpawlowski** [comment]
as said, this was a fresh install and I downgraded to 5.0.2 and upgraded to 5.0.3-develop again (just to see what happens in total, not only for the GS5 cache :-))

**Comment by wintermeyer** [comment]
OK. That special page is an edge case. The heater script does page caching for this page. 
More info about page caching: http://ruby-auf-schienen.de/3.2/page_caching.html

By that I can be sure that even on very slow hardware the very first impression of the WebGUI is a snappy one. I didn't expect anyone to use the very same setup page twice on the same system.

A solution could be that we move the page cache to a new public/cache/ directory. The up-/downgrade scribe should be able to rm -rf public/cache/\* 

I know how to solve this with nginx. But I don't know how to do this in Apache (having public/ and public/cache/ as the same level).

**Comment by jpawlowski** [comment]
Actually the complete GS5-directory get a complete reset with every update so the re-creation of dynamic data content is assured.
Let's close this issue for now and see if there is a real use case coming up during the next few weeks.

Reg. moving the cache to public/cache: I'm not sure if this changes anything. As said /tmp/\* gets purged totally by every update.

**Comment by jpawlowski** [comment]
this occurs again in the first Beta1 build and can be reproduced directly after opening the web gui for the first time.

**Comment by wintermeyer** [comment]
When do you set the version number? => GsParameter.get('GEMEINSCHAFT_BUILDNAME')

**Comment by jpawlowski** [comment]
the environment variable get's updated during every system bootup by the script /etc/init.d/gemeinschaft-prompt.
The ruby initializer script takes care about the import to the database everytime the ruby app gets started.

**Comment by wintermeyer** [comment]
Is the heater rake task started after that? If not it should be moved to a position after that.

**Comment by jpawlowski** [comment]
no, the prompt-task is the very last one. unfortunately I cannot change this as the IP address for the login screen is also being extracted which cannot be done earler.
I will need to transfer those version tasks to a different script which can be run earlier, maybe the helper script with the heater-task itself. Let me think about that....

**Comment by wintermeyer** [comment]
As a work around I deactivate caching for the footer. Please open a new issue once you have a different boot sequence order.

**Comment by jpawlowski** [comment]
this is fixed now, you may reactivate the caching ;)

**Comment by wintermeyer** [comment]
I can't reproduce the problem any more. Must have been fixed somewhere along the road.
