### ISSUE TITLE
ActionView::MissingTemplate in Tenants#show

### ISSUE THREAD

**Issue by spag** [amooma/GS5#117]
ActionView::MissingTemplate in Tenants#show

Showing /opt/GS5/app/views/tenants/_admin_area.html.haml where line #3 raised:

Missing partial tenants/users_table, application/users_table with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :coffee, :haml]}. Searched in:
- "/opt/GS5/app/views"
- "/usr/local/rvm/gems/ruby-1.9.2-p318/gems/sextant-0.2.3/app/views"
  Extracted source (around line #3):

1: = render :partial => 'tenants/sip_accounts_and_phones', :locals => {:tenant => @tenant}
2: 
3: = render :partial => 'users_table', :locals => {:tenant => @tenant}
4: 
5: = render :partial => 'user_groups_table', :locals => {:tenant => @tenant}
6: 
Trace of template inclusion: app/views/tenants/show.html.haml

Rails.root: /opt/GS5

Application Trace | Framework Trace | Full Trace
app/views/tenants/_admin_area.html.haml:3:in `_app_views_tenants__admin_area_html_haml___42815191_80357690'
app/views/tenants/show.html.haml:11:in`_app_views_tenants_show_html_haml___1062136419_101903670'
Request

Parameters:

{"id"=>"2"}
Show session dump

Show env dump

Response

Headers:

None

**Comment by wintermeyer** [comment]
I can not replicate this error for http://0.0.0.0:3000/tenants/2

Is this a fresh Github develop version?

**Comment by spag** [comment]
Yes a fresh gs5_1301200538-develop.iso in live CD mode.

works:
http://192.168.0.151/page/beginners_intro 

fails:
http://192.168.0.151/tenants/2

**Comment by jpawlowski** [comment]
I cant' replicate this either (at least not with my fresh installation, I will try the live-system once more)

**Comment by spag** [comment]
I have two development servers (git install) + one VM with a ISO install. All showing exactly the same error. Strange.

**Comment by jpawlowski** [comment]
Did you try another browser?

**Comment by wintermeyer** [comment]
I close this one. I can't replicate the error. Please open a new issue if it happens again.

**Comment by spag** [comment]
Tried it with any browser I could lay my hands on - I get still this ActionView::MissingTemplate in Tenants#show

**Comment by spag** [comment]
I've found the culprit!

Some files seem to be missing in "app/views/tenants".
The moment I've created "_users_table.html.haml" and "_user_groups_table.html.haml" the error disappeared.
