### ISSUE TITLE
ActiveModel::ForbiddenAttributes in CallRoutesController#create

### ISSUE THREAD

**Issue by spag** [amooma/GS5#119]
http://192.168.0.151/call_routes/new on  gs5_1301200538-develop.iso throws:

ActiveModel::ForbiddenAttributes in CallRoutesController#create

ActiveModel::ForbiddenAttributes
Rails.root: /opt/GS5

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"ZNJWF+s81u/q7wo6peTf860f5VZ2iRnxyzOtthtiQiE=",
 "call_route"=>{"routing_table"=>"outbound",
 "name"=>"gateway",
 "endpoint_type"=>"gateway",
 "endpoint_id"=>"1"},
 "commit"=>"Submit"}
Show session dump

Show env dump

Response

Headers:

None

**Comment by jpawlowski** [comment]
+1
