### ISSUE TITLE
Auto-SIP accounts should not have a voicebox

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#12]

**Comment by wintermeyer** [comment]
Please define "Auto-SIP account".

**Comment by jpawlowski** [comment]
I mean the SIP account which is auto-created during auto-provisioning

**Comment by wintermeyer** [comment]
@spag Julian has a point here. Please take care of it if it makes sense for you too.

**Comment by spag** [comment]
We need a "voicemail_enabled" booelan in the SipAccount model than and have to ensure it gets disabled when an account is created by the provisioning controller.

**Comment by wintermeyer** [comment]
We have bigger fish to fry. I moved this to 5.2.

**Comment by spag** [comment]
Fixed.
