### ISSUE TITLE
read/unread voice messages

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#122]
I think the icon indicating a new voice message in /sip_accounts/4/voicemail_messages works the wrong way around.
The small envelope does not show up if there is a new message but instead appears after I actually read the message. I guess the envelope should be there for new messages, not for old ones...

![Screen Shot 2013-01-20 at 17 13 09](https://f.cloud.github.com/assets/75446/81726/02bcf4c8-6355-11e2-9cfd-5dc86d8839e3.png)

**Comment by spag** [comment]
It's displayed besides the time stamp generated when the message was marked as read. One could find a better icon though.

**Comment by jpawlowski** [comment]
okaaay, a closed envelope shows a message as being read, allright ;-)

**Comment by spag** [comment]
Fix: This particular icon should only be used if the "intelligence_agency" flag is "true"

**Comment by jpawlowski** [comment]
As the icon is currently not appearing anymore lets take this as n.a. for now and close the ticket.
