### ISSUE TITLE
Add a 'Trunk Access Code' to GemeinschaftSetup

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#126]
Let the admin enter a trunk access code during the setup. e.g. 0 for Germany and 9 for the US.

**Comment by wintermeyer** [comment]
Node by @spag 
---cut---
Einfach statt des '' in den Aufruf von "CallRoute.factory_defaults_prerouting" eintragen.
---cut---

**Comment by spag** [comment]
CallRoute.factory_defaults_prerouting(@gemeinschaft_setup.country.country_code, 
@gemeinschaft_setup.country.trunk_prefix, 
@gemeinschaft_setup.country.international_call_prefix, 
@gemeinschaft_setup.trunk_access_code, 
@gemeinschaft_setup.default_area_code
)

**Comment by wintermeyer** [comment]
Closed by 2e5789b
![Bildschirmfoto 2013-02-02 um 15 36 08](https://f.cloud.github.com/assets/69770/120860/23602236-6d46-11e2-8776-37de4791dae1.png)
