### ISSUE TITLE
monAMI: read User database from MySQL instead of SQlite

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#128]
currently mon_ami uses /opt/GS5/db/development.sqlite3 for it's user database.
This should be changed to MySQL for production and development installations (only test environment should use SQlite db)

**Comment by ip6li** [comment]
May support also Postgres SQL

**Comment by spag** [comment]
Fixed in commit 6a1961283914a6b87400bf0b7b492fa9f8692c03
