### ISSUE TITLE
Fax Sendebericht

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#129]
Es wäre hilfreich, wenn man nicht nur das original Fax ansehen kann, sondern sich auch das Fax mit einem Sendebericht herunterladen kann, wie man es von einem normalen Fax her kennt.
Mit Faxkennung, Nummer, Uhrzeit, Datum und erfolgreich gesendet.

**Comment by wintermeyer** [comment]
Aktuell ist das Thema für uns von keiner Bedeutung. Wenn mal jemand das Feature braucht und die Entwicklung bezahlt, dann bauen wir es gerne ein.
