### ISSUE TITLE
Mail2Fax

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#130]
Um sich das geklicke der GUI zu ersparen, wäre eine Mail2Fax Funktion sehr hilfreich. Dann natürlich als Antwort mit einem Sendebericht.

**Comment by jpawlowski** [comment]
Sowas wird schwierig. Man müsste den Mail-Absender prüfen, damit man das richtig zuordnen kann. Trotzdem öffnet man damit Spammern ein großes Tor. Sowas ist nicht unbedingt etwas, was eine Telefonanlage machen/abfangen sollte.

Ich verstehe aber den Wunsch. Für direkt aus dem Internet erreichbare Server ist das allerdings tödlich, einen Mail-Gateway davor zu haben währe mehr als empfehlenswert. Mal sehen wie sich so etwas umsetzen ließe.

**Comment by ip6li** [comment]
Abgesehen davon, dass die Installation von Gemeinschaft direkt im Internet schon sehr fragwürdig wäre, ist gegen eine Mail2Fax Lösung im Intranet nichts zu sagen und auch sehr sinnvoll. Per Default kann man ja den Postfix an ::1 binden. Interessant wäre es natürlich, Hylafax mit Gemeinschaft 5 so zu "verheiraten" wie es schon in Gemeinschaft 3.1 der Fall war. T.38 klappt mit Freeswitch, auf der Hylafax Seite ist jedoch t38modem ein eher unerfreuliches Thema. Die Einbindung von Libreoffice für Office Files via Fax wäre dann auch kein Problem mehr.

**Comment by getsolveit** [comment]
Wozu brauch man denn Hylafax? Es würde doch reichen, wenn man ein Postfach hat, worauf ein Task zugreift und den PDF Anhang und den Betreff kopiert und dann versendet.

**Comment by spag** [comment]
@ip6li Was ist an einer GS5 im Interenet fragwuerdig? Jedes erreichbare System braucht immer eine Abwaegung von Nutzen und Risiko. Ich weiss von mehreren GS5 im Internet die auch jeden Tag Angriffen ausgesetzt sind.

AFAIR ist das in GS4 so geloest. Die Mails mit PDF anhang einfach von einem POP3 Postfach geholt werden. Damit muss sich die Telefonanlage nicht um das Mailsystem kuemmern.

**Comment by getsolveit** [comment]
Das würde mir persönlich auch reichen, ist die Umsetzung schwierig?

**Comment by wintermeyer** [comment]
Ein Mail2Fax Gateway ist technisch gar kein Problem. Ich sehe aber gerade keine Möglichkeit das finanziert zu bekommen. Das ist so ein typisches "wäre nett, aber bezahlen möchte ich dafür nicht" Feature.
