### ISSUE TITLE
Change default fax directory to /var/opt

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#131]
needed for backup/restore function from #39

**Comment by wintermeyer** [comment]
Please change the config of that directory in `config/backup.rb` too.

**Comment by jpawlowski** [comment]
Could this be done in 5.1 already somehow?
Looking at #184 this might be useful.

**Comment by spag** [comment]
fixed commit 2b3892ac24bb61c4814e0afe141bf53765fb1e4b
