### ISSUE TITLE
Better tooltip for GS_VERSION and GS_BUILDNAME

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#140]
I like this kind of tooltip:
![Screen Shot 2013-01-26 at 14 12 13](https://f.cloud.github.com/assets/75446/99772/15146516-67ba-11e2-8435-06d2d753d3dc.png)

but I have no idea how to get this pretty thing for this:
![Screen Shot 2013-01-26 at 14 13 07](https://f.cloud.github.com/assets/75446/99773/267926b6-67ba-11e2-9f61-05ec00469d74.png)

**Comment by wintermeyer** [comment]
done.
