### ISSUE TITLE
Could not find table 'sip_registrations'

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#144]
URL:
http://0.0.0.0:3000/tenants/2/sip_accounts/1

I guess a migration is missing.

![Bildschirmfoto 2013-01-28 um 12 25 59](https://f.cloud.github.com/assets/69770/102821/9111a154-693d-11e2-9507-1f869abdc52b.png)

**Comment by spag** [comment]
fixed in commit fd95d2c2fcc50418cdb23f34b21bcfe04d9cc1de
