### ISSUE TITLE
request.env['REMOTE_USER'] authentification

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#145]

**Comment by wintermeyer** [comment]
User.find_by_user_name(request.env['REMOTE_USER'])

**Comment by wintermeyer** [comment]
done. 731443c

**Comment by duebel-** [comment]
You can test this when you protect the /opt/GS5/public folder with basic authentication. The web server will set REMOTE_USER after a successful authentication.

see http://httpd.apache.org/docs/2.4/mod/mod_authn_core.html#authtype
