### ISSUE TITLE
Control PBX features via DTMF during a call.

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#146]
Let non SIP phones use PBX features via DTMF input.

CC @duebel- @antilo

Please add needed features as comments to this issue.

Needed features:
- Hold/Park
- Transfer
- Blind transfer

**Comment by wintermeyer** [comment]
# Workflows

A uses a connection which sends DTMF inband. B is a normal SIP-Phone. The dialed codes are just examples.

## Attended transfer
- A calls B
- A enters _1_1#
- B gets parked in the parking lot 1
- A hangs up
- A calls C
- A enters _1_1#
- C gets connected to B

## Park a call
- A calls B
- A enters _1_1#
- B gets parked in the parking lot 1
- A hangs up
- A calls _1_1#
- A gets connected to B

## Blind transfer
- A calls B
- A enters _2_5678#
- A hangs up
- B gets connected to 5678

Please add a comment if anything doesn't make sense.

**Comment by duebel-** [comment]
Park a Call
- A cannot call _1_1#. We need a real number here.

maybe better: A hangs up, A calls 999, A enters _1_1#, A gets disconnected from 999 and connected to B

**Comment by wintermeyer** [comment]
Calling _1_1# has the major advantage that the user can put that on speed dial. Calling 999 would mean to be connected to an IVR and having to enter it manually.

BTW: '*' is just an example. That will become '99' or something.

**Comment by spag** [comment]
The star code _1_1# is just an example and is handled by the routing engine. You can put virtually anything in there.
It could be 991 or anything else Lua pattern matching is able to transform into a function name (e.g. "f-park-1")

**Comment by spag** [comment]
The functionality described above is already implemented and can be tested in the newest development builds.
@duebel- If your tests proved the DTMF detection to be reliable and the functionality fits your needs we could probably close this issue.

**Comment by duebel-** [comment]
Recognition is reliable. Functionality is sufficient. But I think we should not close this issue until issue #228 is resolved.
