### ISSUE TITLE
Let admins reset the prerouting table from GUI

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#153]
If users do a lot of testing the prerouting table might be corrupted and hard to correct.
There should be a reset button for admins to easily reset the prerouting table to default settings.

**Comment by wintermeyer** [comment]
I prefer the user to reinstall the system. Installation is easy and fast.

**Comment by jpawlowski** [comment]
Yep or just do a `gs-update --factory-reset` which is pretty much the same.

However if you have a lot of configuration stuff done already a complete reset is probably not what you really want ... e.g. complex gateway configurations and in/out routings.

If we had #120 we might just use the system reset and import gateway and call route settings (without the prerouting part) afterwards.

**Comment by spag** [comment]
One could add a controller action to invoke the "CallRoute.factory_defaults_prerouting" method to reset the table to defaults:

factory_defaults_prerouting(country_code, national_prefix,
international_prefix, trunk_prefix, area_code)

**Comment by wintermeyer** [comment]
I don't want to go in that direction for now. Please have to a) know what they do or b) be able to reinstall.

We simply have way bigger fish to fry.
