### ISSUE TITLE
No mail delivery on incoming messages

### ISSUE THREAD

**Issue by fox69** [amooma/GS5#154]
2013-02-02 12:42:27.733544 [ERR] mod_lua.cpp:198 /usr/share/lua/5.1/socket.lua:13: module 'socket.core' not found:
        no field package.preload['socket.core']
        no file '/usr/share/freeswitch/scripts/socket/core.lua'
        no file '/usr/share/lua/5.1/socket/core.lua'
        no file './socket/core.so'
        no file './libsocket/core51.so'
        no file '/usr/local/lib/lua/5.1/socket/core.so'
        no file '/usr/local/lib/lua/5.1/libsocket/core51.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './socket.so'
        no file './libsocket51.so'
        no file '/usr/local/lib/lua/5.1/socket.so'
        no file '/usr/local/lib/lua/5.1/libsocket51.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/share/lua/5.1/socket.lua:13: in main chunk
        [C]: in function 'require'
        /usr/share/lua/5.1/socket/http.lua:11: in main chunk
        [C]: in function 'require'
        /usr/share/freeswitch/scripts/http_request.lua:5: in main chunk

**Comment by wintermeyer** [comment]
Which version of Gemeinschaft do you use?

**Comment by wintermeyer** [comment]
Closed #155
