### ISSUE TITLE
No mail delivery on incoming messages

### ISSUE THREAD

**Issue by fox69** [amooma/GS5#155]
URL which triggered the bugreport is: /tenants/2/users/1
GS5 buildname: 1301281724

2013-02-02 12:42:27.733544 [ERR] mod_lua.cpp:198 /usr/share/lua/5.1/socket.lua:13: module 'socket.core' not found:
        no field package.preload['socket.core']
        no file '/usr/share/freeswitch/scripts/socket/core.lua'
        no file '/usr/share/lua/5.1/socket/core.lua'
        no file './socket/core.so'
        no file './libsocket/core51.so'
        no file '/usr/local/lib/lua/5.1/socket/core.so'
        no file '/usr/local/lib/lua/5.1/libsocket/core51.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './socket.so'
        no file './libsocket51.so'
        no file '/usr/local/lib/lua/5.1/socket.so'
        no file '/usr/local/lib/lua/5.1/libsocket51.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/share/lua/5.1/socket.lua:13: in main chunk
        [C]: in function 'require'
        /usr/share/lua/5.1/socket/http.lua:11: in main chunk
        [C]: in function 'require'
        /usr/share/freeswitch/scripts/http_request.lua:5: in main chunk

**Comment by spag** [comment]
lua-socket:i386 provides:

/usr/lib/i386-linux-gnu/lua/5.1/socket
/usr/lib/i386-linux-gnu/lua/5.1/mime
/usr/lib/i386-linux-gnu/liblua5.1-socket-unix.so.2.0.0
/usr/lib/i386-linux-gnu/liblua5.1-mime.so.2.0.0
/usr/lib/i386-linux-gnu/liblua5.1-socket.so.2.0.0
/usr/share/lua/5.1/socket
/usr/share/lua/5.1/socket/url.lua
/usr/share/lua/5.1/socket/ftp.lua
/usr/share/lua/5.1/socket/http.lua
/usr/share/lua/5.1/socket/tp.lua
/usr/share/lua/5.1/socket/smtp.lua
/usr/share/lua/5.1/mime.lua
/usr/share/lua/5.1/ltn12.lua
/usr/share/lua/5.1/socket.lua
/usr/lib/i386-linux-gnu/liblua5.1-mime.so.2
/usr/lib/i386-linux-gnu/liblua5.1-socket.so.2
/usr/lib/i386-linux-gnu/liblua5.1-socket-unix.so.2
/usr/lib/i386-linux-gnu/lua/5.1/socket/core.so
/usr/lib/i386-linux-gnu/lua/5.1/socket/unix.so
/usr/lib/i386-linux-gnu/lua/5.1/mime/core.so

**Comment by wintermeyer** [comment]
@jpawlowski Are they installed in GBE?

**Comment by jpawlowski** [comment]
Yes:
https://github.com/amooma/GBE/blob/develop/config.v3/package-lists/07-gs5.list.chroot#L8

files are existing in current builds

**Comment by wintermeyer** [comment]
@fox69 Please provide a little bit more information. What did you do? How did you configure the system?

**Comment by jpawlowski** [comment]
This isse can be reproduced with a standard beta installation.
Must be something with include search path in the lua scripts

**Comment by spag** [comment]
fixed in commit 87c71a3b6f33d28b03a8bde95cc3f921400dc8ae
