### ISSUE TITLE
Endpoint don't be saved on create or edit an call route

### ISSUE THREAD

**Issue by DennisM84** [amooma/GS5#157]
URL which triggered the bugreport is: /call_routes/32
GS5 buildname: 1302021217-develop

When i create a call route for an sip gateway the endpoint was not saved. Edit the call route is the same.
![Screenshot_2013-02-03-15-02-33](https://f.cloud.github.com/assets/3463543/121874/81ed2ba4-6e0a-11e2-90a9-2e63235e0d08.jpg)

**Comment by wintermeyer** [comment]
Should be fixed by 5a58c0c 
Please check it with the next beta and open a new issue in case it still doesn't work.
