### ISSUE TITLE
Delete a phonenumber from sip account gets error

### ISSUE THREAD

**Issue by DennisM84** [amooma/GS5#170]
URL which triggered the bugreport is: /tenants/2/sip_accounts/1
GS5 buildname: 1302021217-develop (5.1-beta4-develop)

When i will delete a phonenumber an confirm the question if i will delete i become an error. See the screenshot for more details.

![delete_phonenumber](https://f.cloud.github.com/assets/3463543/152048/82c609dc-75ae-11e2-8a80-fec748df577b.png)

**Comment by wintermeyer** [comment]
I can't replicate this error. Please use today's nightly build.
