### ISSUE TITLE
Kein Klingelton/Freizeichen

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#173]
Mit dem Update von heute Nacht gibt es keinen Klingelton/Freizeichen mehr wenn man von Intern nach Extern ( über Berofix oder einen SIP Provider ) telefoniert.
Intern gibt es ein Freizeichen.
Telefonieren klappt.

**Comment by wintermeyer** [comment]
Welche Telefone und welche Build Nummer?

**Comment by getsolveit** [comment]
Snom 320 #1301231254

**Comment by wintermeyer** [comment]
I can't replicate this problem with beta 5.
