### ISSUE TITLE
GUI funktioniert nicht mehr.

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#174]
Die GUI  lässt sich nicht mehr aufrufen nach einem Update von eben.
Ausgeführt habe ich noch den Befehl aus dem Issue #161 
Dann habe ich einen Reboot ausgeführt.

![error_gs51_beta4](https://f.cloud.github.com/assets/3115028/152824/5ff92656-75da-11e2-8193-bb57c703d5ed.png)

**Comment by wintermeyer** [comment]
Bitte mit der CD neu installieren. Das Update per Skript wird in der Beta nicht supportet.

**Comment by getsolveit** [comment]
Nach einem Update von gestern 22 Uhr, funktioniert die GUI auch wieder.
