### ISSUE TITLE
Clean up fax tiff files in /tmp

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#176]
It seems that incoming faxes are saved as tiff files in /tmp but never get deleted there.

**Comment by spag** [comment]
Could be a problem with access permissions. Does a "Raw fax file could not be deleted ... " error occur?

**Comment by wintermeyer** [comment]
I didn't see one. Where would such an error been displayed?

**Comment by spag** [comment]
/opt/GS5/log/production or development

**Comment by spag** [comment]
Seems to be a file permissions problem:

Errno::EPERM (Operation not permitted - /tmp/fax_in_15d2fbd8-a870-422b-9fd1-ef5e27d9d351.tiff):
  app/controllers/trigger_controller.rb:100:in `delete'
  app/controllers/trigger_controller.rb:100:in`block in fax'
  app/controllers/trigger_controller.rb:69:in `fax'

**Comment by wintermeyer** [comment]
Worst case: We set up a whenever cronjob which deletes old tiffs in /tmp. That would be ok for a work around.

**Comment by spag** [comment]
Changing the tiff-file directory and setting proper permissions during the installation process should solve this issue without involving any active components (e.g. cron).

**Comment by duebel-** [comment]
mkdir /opt/GS5/tmp/fax
chown freeswitch:gemeinschaft /opt/GS5/tmp/fax
chmod g+ws /opt/GS5/tmp/fax

alter
/opt/GS5/misc/freeswitch/scripts/dialplan/fax.lua
/opt/GS5/app/controllers/trigger_controller.rb
accordingly.

**Comment by wintermeyer** [comment]
Moved to 
https://github.com/amooma/GS5/issues/184
https://github.com/amooma/GBE/issues/154
