### ISSUE TITLE
/opt/freeswitch/sounds/de/de ist missing

### ISSUE THREAD

**Issue by ip6li** [amooma/GS5#179]
It is referenced by some IVR functions.

Workaround:
mkdir /opt/freeswitch/sounds/de
cd /opt/freeswitch/sounds/de
ln -s ../en/us de

you get english voiceprompt, but that's better than failing functions.

**Comment by jpawlowski** [comment]
German voice prompts are not ready for production yet but you may install them as an add-on:

`gs-addon list`
