### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by ip6li** [amooma/GS5#181]
GS5 should also support SIPS/SRTP as described at http://wiki.freeswitch.org/wiki/SIP_TLS which requires some additional steps while set up GS5 server and each client.
- while install: Create CA certificate
- while install: Create GS5 server certificate
- while install: set up Freeswitch parameters for TLS
- while set up phone: Create client certificate signed by CA mentioned above

**Comment by jpawlowski** [comment]
The need for a CA is indeed the reason this setup is currently not included in GS5.
It it likely that there will be a add-on script to ease setup some day (if anybody writes it) but as this is an advanced feature it's unlikely this will be enabled by default (also for other reasons as TLS can sause other difficulties in special scenarios).
