### ISSUE TITLE
GRUB + LILO + apt Installer Probleme auf einem PC

### ISSUE THREAD

**Issue by schraube** [amooma/GS5#183]
Hallo,
also ich versuche mal so gut wie es mir möglich ist das Problem bei der Installation auf einem PC zu beschreiben.
Bei der Intsallation trat folgender Fehler auf:
Dateien für "apt" konnten nicht von der CD geladen werden. Auch konnte kein Bootloader installiert werden. Weder GRUB noch LILO.
Ich musste die Installation abbrechen. 
Eine Installation auf einer Virtuellen Maschine funktionierte aber tadellos.

**Comment by wintermeyer** [comment]
Welchen Datennamen hatte das ISO-Image? Welche Version von Gemeinschaft ist das? Welche Hardware ist das?

**Comment by schraube** [comment]
Hi,
also es ist die Version von heute Morgen. GS5-beta5
Die Installation der 5.0 Version war kein Problem.
Wie kann ich genaue Daten über den Rechner auf dem ich die 5.1 Version installieren möchte heraus finden?
VG
Stefan

**Comment by jpawlowski** [comment]
Ich fürchte das ist alles etwas zu schwammig. Schreib bitte einmal den genauen Wortlaut der Meldungen, die du bekommst.
War die Festplatte vorher schon in Gebrauch? Ggf. hilft es diese Platte vorher von allen Partitionen zu befreien und einen neuen Master Boot Record vom Typ MBR zu setzen (GUID geht vermutlich nicht). Welche Größe hat die Festplatte?

**Comment by schraube** [comment]
habe die 5.0 Version wieder aufgespielt, da ich dringend ein funktionierendes System benötige (ja ich weiss, das es schön blöd von mir ist)
Wie kann ich die Platte komplett löschen?
Am 18.02.2013 um 09:55 schrieb Julian Pawlowski:

**Comment by jpawlowski** [comment]
z.B. mit fdisk oder parted

**Comment by jpawlowski** [comment]
Wie genau hast du denn die Installation durchgeführt? Hast du eine CD gebrannt oder das ISO auf einen USB Stick gepackt? Ggf. ist dabei auch einfach etwas schief gegangen bei der 5.1er.

**Comment by schraube** [comment]
Also..
das ISO Image heruntergeladen und auf eine CD gebrannt.
In den Rechner geworfen und installiert. So habe ich das eigentlich immer gemacht....

**Comment by schraube** [comment]
Die Installation lief ja auch rund, bis zu der Stelle, an der "apt" installiert werden sollte.
Kein "apt" kein Bootloader nichts konnte ich danach installieren.....

Kann als gsmaster kein fdisk vornehemen....

**Comment by jpawlowski** [comment]
gsmaster kann mit sudo zum root werden (siehe Wiki), aber fdisk kannst du nicht aus einem laufenden System heraus machen. Dafür musst du von einem Rettungssystem o.ä. starten. Das führt aber zu weit hier.

Ich habe leider keinen PC, um das mal zu testen. Sehr wahrscheinlich ist aber, dass etwas mit deiner Rechner-Konstellation anormal ist, wenn es bei einer virtuellen Maschine funktioniert (denn daran sieht man ja, dass "apt" und alle nötigen Pakete mit im ISO Image enthalten sind).
Versuch mal das ganze mit einem USB Stick. Ich hatte auch schon öfters Ärger mit teils älteren CD-Rom Laufwerken, aber auch mit nagelneuen, die einfach den CD Rohling nicht richtig gefressen und irgendwann das Lesen aufgegeben haben.

**Comment by schraube** [comment]
installiere gerad auf einem anderen Rechner, werde gleich berichten....

**Comment by schraube** [comment]
....aber ich denke, das es jetzt erst mal Zeit für einen Cappucion ist -:)

**Comment by schraube** [comment]
Die Installation auf einem anderen Rechner hat funktioniert!
Das lag wohl, wie Du schon vermutest hast, an dem Laufwerk. Habe auf dem Rechner dann wieder die Version 5.02 ohne probleme installiert. Komisch!
Versuche nun die 5.1 zu konfigurieren.....

**Comment by jpawlowski** [comment]
Freut mich, dass wir den Fehler finden konnten ;-)
