### ISSUE TITLE
/var/opt/gemeinschaft/fax/in

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#184]
Save tiff files of faxes in the following directories:
/var/opt/gemeinschaft/fax/in
/var/opt/gemeinschaft/fax/out

CC @jpawlowski

**Comment by jpawlowski** [comment]
we might want to use /var/spool/freeswitch for the incoming faxes before GS5 picks them up for final destination in /var/opt/gemeinschaft/fax/in

**Comment by jpawlowski** [comment]
commit 4f89e10f2aaeeeb2696f8e456149e8f66e7bb02b does the first part I guess

**Comment by jpawlowski** [comment]
The spooling part is done. However task from #131 should be done already now, otherwise fax documents get lost when using gs-update as they are currently stored in /opt/GS5/upload

**Comment by spag** [comment]
Since commit e0bd56db83104a2a38e88af2eadaefd389aa798b the fax_document model / trigger_controller does not have to know an explicit spool directory location. The only place a spool directory has to be set for incoming fax documents is fax.lua then.

**Comment by jpawlowski** [comment]
yep, I'm intentionally mixing something up here :-)
#131 is not about the spooling dir but about the actual target dir for incoming and sent faxes. Just to put your nose on it :-p

The original purpose for this ticket is fulfilled I guess, I'll close it.
