### ISSUE TITLE
Fehler beim löschen einer Rufumleitung.

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#190]
URL which triggered the bugreport is: /sip_accounts/1/phone_numbers/10
GS5 buildname: 1302191124-develop (5.1-beta6-develop)

ActiveRecord::StatementInvalid in CallForwardsController#destroy 
Mysql2::Error: Unknown column 'softkeys.call_forward_id' in 'where clause': SELECT `softkeys`.\* FROM `softkeys`  WHERE `softkeys`.`call_forward_id` = 2

Rails.root: /opt/GS5

Application Trace | Framework Trace | Full Trace 
app/models/call_forward.rb:146:in `deactivate_connected_softkeys'
app/models/call_forward.rb:122:in`block in destroy_all_similar_callforward_rules_of_the_parent_sip_account'
app/models/call_forward.rb:120:in `destroy_all_similar_callforward_rules_of_the_parent_sip_account'
app/models/call_forward.rb:217:in`check_if_other_callforward_rules_have_to_be_destroyed'
app/controllers/call_forwards_controller.rb:72:in `destroy'

Request

Parameters: 
{"_method"=>"delete",
 "authenticity_token"=>"2jvY+eki2SdpMlRLwinCiOywXWqv5NJMc1/hzdsP38I=",
 "phone_number_id"=>"10",
 "id"=>"4"}

Show session dump

Show env dump

Response

Headers: 
None

**Comment by spag** [comment]
fixed in commit 86a77e472a54f6091eebffae42d638c3c826c13d
