### ISSUE TITLE
Area code in setup controller with/without leading 0

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#193]
currently the comment states one need to enter the local area code with a leading 0.
in fact when doing it that way no prerouting entry will be created. Instead the local area code needs to be without leading 0 (e.g. 89 instead of 089) to work.
either the description or the behavior should be adjusted :-)

**Comment by spag** [comment]
I think it would be better to alter the description. There are no area codes out there starting with 0 at least not in countries using 0 as the trunk prefix (e.g. Germany).

**Comment by jpawlowski** [comment]
yep ;)
