### ISSUE TITLE
Include additonal files into backup

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#195]
Backup is currently missing a lot of other files from `/var/opt/gemeinschaft/freeswitch`, e.g. greetings a user recorded for his voicebox

**Comment by wintermeyer** [comment]
It currently has the following directory structure:

```
gsmaster@gs5:/var/opt/gemeinschaft/freeswitch$ tree
.
├── conf
│   ├── freeswitch.serial
│   └── freeswitch.xml
├── db
├── recordings
├── storage
└── voicemail

5 directories, 2 files
gsmaster@gs5:/var/opt/gemeinschaft/freeswitch$
```

@spag Which of those directories do we have to include into the backup?

**Comment by jpawlowski** [comment]
Normally all files on /var/opt/gemeinschaft are supposed to be backed up.
If that's not the case we should move it back to the standard directory.

**Comment by wintermeyer** [comment]
I added recordings and voicemail to the backup/restore. a865b1f 

@jpawlowski I see your point but I don't have the time to move this stuff around.
