### ISSUE TITLE
Rufumleitung führt zu einem Logout bei Hotdesk-Telefonen

### ISSUE THREAD

**Issue by duebel-** [amooma/GS5#197]
Trotz fehlerfreier Programmierung hat sich eine kleine Ungewöhnlichkeit eingeschlichen. ;-)

Aktivieren oder Deaktivieren von Rufumleitungen im WebUI führt zu einem Logout des Users aus dem Hotdesk-Telefon mit anschließendem Reboot desselben.

Aktivieren oder Deaktivieren der Rufumleitung am Telefon mittels Feature Code führt nicht zu diesem Verhalten.

Aktivieren oder Deaktivieren der Rufumleitung am Telefon per Softkey führt ebefalls zum Logout usw.

Seite, die die Ungewöhnlichkeit auslöst: /phone_numbers/2/call_forwards/16/edit
Beteiligtes Telefon: Snom 821

**Comment by spag** [comment]
could be affected by commit 5dcdeb1c1f8c53fd80a0443d61a289e583091416

**Comment by spag** [comment]
Should be fixed by now. Please feel free to reopen this ticket if the issue is still present in the newer builds.
