### ISSUE TITLE
Rufgruppen Strategie

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#198]
Hallo,

ich setzte die aktuelle Developer Version ein.

Wenn ich eine Rufgruppe erstelle, in der alle gleichzeitig klingeln, gibt es keine Probleme, alle Telefone klingeln und man kann an jedem Telefon den Anruf entgegen nehmen.

Verwende ich allerdings die andere Variante dann funktioniert das Ganze irgendwie gar nicht mehr.

Signalisiert wird alles korrekt!

Ich konnte leider noch keinen konkreten Fall nachbilden.

Jedenfalls kommt die Verbindung zu 90% nicht zu Stande, wenn man abhebt. Hier geht es hauptsächlich um den 2. 3. 4. etc. in der Rufgruppe. Der 1. kann das Gespräch meistens annehmen, wenn noch kein anderer klingelt.

Ich muss aber dazu sagen, dass ich die Rufgruppe in einer anderen Form noch nie eingesetzt habe. Kann also nicht sagen, ob es mit der 5.02 funktioniert hat.

Gruß
Oliver

**Comment by wintermeyer** [comment]
Wir brauchen ein reproduzierbare Phänomen, um ein eventuelles Problem angehen zu können.

**Comment by getsolveit** [comment]
Liefer ich Montag, dann kann ich die Fälle nochmal durchtesten.
