### ISSUE TITLE
Call history headers

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#200]
URL which triggered the bugreport is: /sip_accounts/2/call_histories?type=
GS5 buildname: 1302240346-develop (5.1-beta6-develop)

Headers seem to be inspecific, I can't image what those whould should me:
- misc
- Avatar
  ![Screen Shot 2013-02-24 at 23 14 37](https://f.cloud.github.com/assets/75446/190143/d0232744-7ecf-11e2-9bb4-dafaa478958b.png)

**Comment by spag** [comment]
Call history views have been refactored.
