### ISSUE TITLE
Einstellungen Amtszugangsberechtigung pro User im GUI

### ISSUE THREAD

**Issue by MSTKMSTK** [amooma/GS5#201]
FEATURE REQUEST:
1. Siprufnummer für jeden User für Externwahl frei wählbar in den Usereinstellungen im GUI.
2. Benutzer bzw. Gruppe für externe Wahl sperren im GUI --> reine interne Nebenstelle ( aber Notruf  erlaubt  / Nummern aus Telefonbuch erlaubt ) evtl. sogar Zeitbeschränkt

**Comment by wintermeyer** [comment]
Bitte immer nur ein Feature-Request pro Issue. Hilfreich wäre auch eine Begründung für das Feature-Request.
