### ISSUE TITLE
ACD position prompt

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#202]
Using the german language the prompt to inform about the position is wrong.
It says:

"Sie sind an Position 1 AUF LEITUNG".

The last part in capital letters comes from the english language, playing this file in german language is obsolete and needs to be removed (somehow).

**Comment by spag** [comment]
Sorry, I have not the finest idea what you're up to. Do we have to change this in the table used for generating voice prompts?

**Comment by jpawlowski** [comment]
Use case: Create a default ACD (with unconditional entry) and listen carefully ;-)
It says "Sie sind an Position 1 auf Leitung" which is "You are number 1 in line" in english. The german grammar is not correct here, this is what needs to be corrected somehow.

**Comment by spag** [comment]
@jpawlowski Thank you for clarifying that point.

Fixed in commit 2a9e544a6a1f846fa1291c62a85cf7ef019ced64
