### ISSUE TITLE
Changing Pin via voicemailbox not working

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#203]
Trying to change my PIN it just says "enter your pin followed by pound" and when I do so it just goes back to the previous menu without any further information.

**Comment by spag** [comment]
The macro "voicemail_change_pass_success" seems to be missing in freeswitch.xml. The PIN seems to be changed though.

<macro name="voicemail_change_pass_success">
  <input pattern="^(.*)$">
    <match>
      <action function="play-file" data="voicemail/VOICEPROMPT_FILE_NAME.wav"/>
    </match>
  </input>
</macro>
