### ISSUE TITLE
Play tone when entering/leaving a conference

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#207]
FS guys seem to have prepared sound files to have the conference just giving simple tones e.g. when entering/leaving a conference (or in addition to saying "person xy just entered/left").

I would love to have this configurable for each conference.

Announcing the name should be optional for entering and leaving separately, just the tone should be default especially for leaving confcalls. Bigger rounds get a lot of interruptions if there are people leaving earlier and just a small tone is much less disturbing.

(I'm used to this kind of behavior from the Siemens and NSN area)

Available sound files:
conference/conf-entry_tone.wav
conference/conf-exit_tone.wav
conference/conf-ack_tone.wav
conference/conf-nack_tone.wav

Also see
https://github.com/jpawlowski/freeswitch-sounds-tts/tree/master/tone/conference

**Comment by spag** [comment]
Have you tried to set the following parameters in gs_parameters -> conferences -> parameters ?
  enter-sound
  exit-sound
  ack-sound
  nack-sound

http://wiki.freeswitch.org/wiki/Mod_conference#Conference_Parameters

**Comment by jpawlowski** [comment]
I just noticed those parameters a few days ago, let me check on that.
What I can tell already now: The implemented beep (or the tone file if configured) should be before the announcement, not after as it is currently ;-)

**Comment by spag** [comment]
Changed in commit 13658ab197777d0b4870bfa51ac4115a9afed845
