### ISSUE TITLE
Set language for incoming calls according to their source

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#209]
Default language e.g. for voice prompts in the conference, ACD or IVR should be automatically set according to the callers source country.
E.g. if the caller has a +49, +43 or +41 number it should be set to german language, for all other countries english should be used as default.

However one should still be able to manually configure a default language for incoming calls (e.g. for anonymous callers).

**Comment by spag** [comment]
The dialplan language can be set in gs_parameters ->  dialplan, parameters, default_language and should be English by default.

The functionality you requested can be easily set by an "inbound" route:

<route_element action="set" mandatory="false" pattern="^%+49(%d+)$" replacement="de" var_in="caller_id_number" var_out="language"/>

Again: The GS5 router is a mysterious and powerful device and its mystery is only exceeded by its power. (TM)
