### ISSUE TITLE
Outbound SIP connection blocked by firewall

### ISSUE THREAD

**Issue by burka** [amooma/GS5#214]
I wasn't able to make outgoing sip connections to our bero*fix box with 5.1-beta6 but found a fix for that, maybe it should get included.

`fs_cli -l 6`:

```
tport.c:3616 tport_send_fatal() tport_vsend(0x8626228): Operation not permitted with (s=19 */192.168.0.114:5060)
nta.c:8348 outgoing_print_tport_error() nta: INVITE (40653849): Operation not permitted (1) with */[192.168.0.114]:5060
```

`tail /var/log/messages`

```
Feb 27 16:43:18 phone kernel: [ 2069.409576] nf_ct_sip: dropping packetIN= OUT=eth0 SRC=192.168.0.113 DST=192.168.0.114 LEN=1307 TOS=0x00 PREC=0x00 TTL=64 ID=25549 PROTO=UDP SPT=5060 DPT=5060 LEN=1287 UID=999 GID=999 
```

A simple 
`rmmod nf_conntrack_sip`
 and 
`echo "blacklist nf_conntrack_sip" > /etc/modprobe.d/blacklist-sip-conntrack.conf`
fixed that. I hope it stays that way.

**Comment by jpawlowski** [comment]
This depends on your actual system environment, e.g. if you have separate subnets or so.
We will keep the netfilter module für SIP enable as a default as it's always necessary to adopt firewalls settings to the local environment.

Your workaround is not exactly what I would recommended. Instead you should just configure Shorewall to not load the SIP netfilter kernel module. To achieve this just edit /etc/shorewall/helpers and disable module nf_conntrack_sip.

However you may just want to adjust port settings etc for nf_conntrack_sip there to keep it active.
