### ISSUE TITLE
Installer: Partitioning fails on ESX 5.0 when no virtual floppy drive is configured

### ISSUE THREAD

**Issue by krissi** [amooma/GS5#217]
The autopartitioning fails when no floppy drive is configured in a esx 5.0.0 virtual machine. See attachment for error message and logfile.

![g5t 2013-03-01 12:58:51](https://f.cloud.github.com/assets/436758/209341/677033cc-8267-11e2-9e38-e285b2332a01.png)
![g5t 2013-03-01 12:57:50](https://f.cloud.github.com/assets/436758/209339/487a9160-8267-11e2-9fc6-96963b048682.png)

Steps to reproduce:
- Create a new virtual machine (Debian 6 x64) profile
- Remove floppy drive from virtual machine
- Boot the iso and follow the instructions

**Comment by jpawlowski** [comment]
GS5 is not an x64 machine, please try x86 profile first.

**Comment by krissi** [comment]
same with x86

**Comment by jpawlowski** [comment]
As we don't see this error using VMware fusion I suggest you just keep the floppy drive during install and remove it afterwards (however I don't see any reason why not to keep it at all).

This issue is basically nothing we can really affect in any way.

**Comment by jpawlowski** [comment]
I was able to reproduce this issue with ESXi 5.0.2, even with default settings.
However ESXi 5.1 does not seem to have this issue, please consider upgrading to ESXi 5.1.
