### ISSUE TITLE
Umleitung nach Zeit

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#218]
Es gab schon einen Fall mit Rufgruppen.

https://github.com/amooma/GS5/issues/198

Der gleiche Fall tritt auch bei einem Call Forwarding nach Zeit auf.

**Comment by spag** [comment]
Was passiert denn genau?

**Comment by getsolveit** [comment]
Es klingelt, aber wenn man abhebt bleibt es still. Umleitung nach Besetzt klappt.
Und wenn man eine Rufgruppe nach Zeit signalisieren lässt, genau der gleiche Effekt.

**Comment by spag** [comment]
Kann das noch jemand nachstellen?

**Comment by getsolveit** [comment]
Ich lad jetzt nochmal das aktuelle Devel und teste es nochmal.

**Comment by spag** [comment]
Please reopen if this issue is still present after Build #1303200520-develop
