### ISSUE TITLE
Exception when deleting conference member

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#219]
URL: /conferences/1/conference_invitees/2
Version: 5.1.0 Branch: master

Deleting a conference member from a conference leads to an exception

Logfile production.log:

```
NameError (undefined local variable or method `conference_invitees_url' for #<ConferenceInviteesController:0xbda6d70>):
  app/controllers/conference_invitees_controller.rb:61:in `destroy'

```

**Comment by spag** [comment]
fixed in commit 7ec2f96979317912b464b801731c5d10be538e6d
