### ISSUE TITLE
Fehler beim Anlegen von Rufumleitungen für Rufgruppe

### ISSUE THREAD

**Issue by jonasvp** [amooma/GS5#224]
URL which triggered the bugreport is: /phone_numbers/4/call_forwards/new
GS5 buildname: 1302281156 (5.1.0)

Wenn ich bei den Telefonnummern einer Rufgruppe versuche, eine Rufumleitung anzulegen, kommt der Fehlerscreen.

Im Log steht:

```
NoMethodError (undefined method `sip_accountable_type' for nil:NilClass):
app/controllers/call_forwards_controller.rb:93:in `spread_breadcrumbs'
```

Wenn ich das gleiche bei der Rufnummer eines Teilnehmers (anstatt einer Rufgruppe) mache, funktioniert es wunderbar.

**Comment by wintermeyer** [comment]
Will be fixed in 5.1.1
