### ISSUE TITLE
SQLite3::SQLException: no such table: detailed_calls

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#225]
http://0.0.0.0:3000/users/1/sip_accounts/1
liefert auf einer reinen Rails Entwicklungsumgebung folgenden Fehler:

```
SQLite3::SQLException: no such table: detailed_calls: SELECT DISTINCT detailed_calls.* FROM detailed_calls WHERE presence_id LIKE '2a7b9712b6db17d6b749@%' OR b_presence_id LIKE '2a7b9712b6db17d6b749@%'
```

Ich nehme an, das da eine Migration für die Tabelle detailed_calls fehlt.

**Comment by spag** [comment]
fixed in commit c98072557273ff4383013f73621061ece34fc6d2

**Comment by wintermeyer** [comment]
I split up the migration into a sqlite3 and an else part. Not nice. But I don't see an other way. 5b4b52f
