### ISSUE TITLE
Breadcrums are missing on /phone_numbers/17/ringtones

### ISSUE THREAD

**Issue by DennisM84** [amooma/GS5#226]
URL which triggered the bugreport is: /phone_numbers/17/ringtones
GS5 buildname: 1302281156 (5.1.0)

Breadcrums are missing..

**Comment by wintermeyer** [comment]
Please provide a screenshot and give more information about the kind of phone_number.

**Comment by DennisM84** [comment]
![Screenshot_2013-03-07-21-50-19](https://f.cloud.github.com/assets/3463543/234084/b10b9124-8768-11e2-8134-801668323643.jpg)

![Screenshot_2013-03-07-21-46-11](https://f.cloud.github.com/assets/3463543/234073/5924a90a-8768-11e2-8d2a-e1c1cc15f29f.jpg)

It is a phone number from an hunt group. Same for ringtone from sip_accounts.. Same bug?

**Comment by getsolveit** [comment]
Sie fehlen auch, wenn man eine Rufumleitung für eine Rufnummer einer Gruppe anlegt oder bearbeiten möchte.

**Comment by spag** [comment]
fixed in commit 61c91cccb00bbc04049d102150929874fc1a08e5
