### ISSUE TITLE
build.amooma.de DNS

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#229]
Create a new DNS entry for build.amooma.de and (more important) repo.amooma.de.

**Comment by jpawlowski** [comment]
having the entry for repo.amooma.de already for GS5.2 release would be good, otherwise people will get errors during installation and running "aptitude update" stating that one repository could not be reached.

**Comment by jpawlowski** [comment]
alternate approach: enabling the webserver on www.amooma.de to reverse-proxy repo.amooma.de and build.amooma.de to the correct server.
this might be an interims solution only though...

**Comment by jpawlowski** [comment]
build.amooma.de is working correctly now.
Could you please also set an A-record for repo.amooma.de to 89.221.14.194?
The issue ticket can be closed afterwards.

**Comment by jpawlowski** [comment]
Stefan did a good job, we can close the ticket ;-)
