### ISSUE TITLE
SSO nach Reboot

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#232]
> Das SigleSignOn funktioniert soweit, bis wir das System rebooten. Danach
> poppt eine Anmeldemaske beim Client auf, welches die AD Auth. Daten aber
> nicht akzeptiert.
> 
> Vermutlich ist hier noch ein Dienst zu starten, bzw.  zu stoppen.

**Comment by duebel-** [comment]
Läuft winbind?

Was sagt "wbinfo -u" auf der shell?

**Comment by wintermeyer** [comment]
```
gsmaster@gs01:~$ wbinfo -u
Error looking up domain users
```

**Comment by duebel-** [comment]
sudo /etc/init.d/winbind start
wbinfo -u

**Comment by wintermeyer** [comment]
@jpawlowski What is the correct syntax to add `/etc/init.d/winbind` in the GS 5.1 runlevel? I need to add this to https://github.com/amooma/GS5/wiki/Single-Sign-On-(with-Active-Directory)

**Comment by jpawlowski** [comment]
It's as simple as `update-rc.d winbind defaults`
