### ISSUE TITLE
Caching issue: SIP-account state not updated

### ISSUE THREAD

**Issue by matis2le** [amooma/GS5#233]
URL which triggered the bugreport is: /tenants/2/sip_accounts
GS5 buildname: 1302281156 (5.1.1)

Please provide your bugreport below this line and update the title of this issue to a more specific one.

central accounts visible on  /tenants/2 seems to be offline but in page  /tenants/2/sip_accounts they have the real state icon

**Comment by matis2le** [comment]
additional info:
2 of my 3 central numbers are connected to a mediatrix gateway for fax
if i configured now the third number for a meeting room phone - all 3 numbers are now updated to online and the snom is visible with MAC and IP in the table. The mediatrix isnt visible with this information (maybe config wrong?)
This is not(!) a browser issue - i tested 3 different browsers and cache cleaning etc.

**Comment by jpawlowski** [comment]
This seems to be a caching issue on the server side.
