### ISSUE TITLE
call histories display should be faster

### ISSUE THREAD

**Issue by duebel-** [amooma/GS5#24]
Rendering of call_histories/_index_core.html.haml is quite slow as seen in production.log below. Time is dependent on number of entries to render:

Started GET "/sip_accounts/4/call_histories" for a.b.c.d at 2012-12-21 10:54:20 +0100
Processing by CallHistoriesController#index as HTML
  Parameters: {"sip_account_id"=>"4"}
  Rendered call_histories/_navigation.html.haml (4.5ms)
  Rendered call_histories/_navigation.html.haml (3.4ms)
  Rendered call_histories/_index_core.html.haml (5816.4ms)
  Rendered call_histories/index.html.haml within layouts/application (5817.7ms)
  Rendered shared/_header.de.html.haml (11.4ms)
  Rendered shared/_system_message.html.haml (1.5ms)
  Rendered shared/_flash.html.haml (0.1ms)
Completed 200 OK in 5898ms (Views: 5803.6ms | ActiveRecord: 44.3ms)

Started GET "/sip_accounts/4/call_histories?type=missed" for a.b.c.d at 2012-12-21 10:54:44 +0100
Processing by CallHistoriesController#index as HTML
  Parameters: {"type"=>"missed", "sip_account_id"=>"4"}
  Rendered call_histories/_navigation.html.haml (3.0ms)
  Rendered call_histories/_navigation.html.haml (2.3ms)
  Rendered call_histories/_index_core.html.haml (6447.3ms)
  Rendered call_histories/index.html.haml within layouts/application (6448.5ms)
  Rendered shared/_header.de.html.haml (15.2ms)
  Rendered shared/_system_message.html.haml (1.3ms)
  Rendered shared/_flash.html.haml (0.1ms)
Completed 200 OK in 6519ms (Views: 6409.3ms | ActiveRecord: 67.2ms)

Started GET "/sip_accounts/4/call_histories?type=received" for a.b.c.d at 2012-12-21 10:54:56 +0100
Processing by CallHistoriesController#index as HTML
  Parameters: {"type"=>"received", "sip_account_id"=>"4"}
  Rendered call_histories/_navigation.html.haml (1.5ms)
  Rendered call_histories/_navigation.html.haml (0.8ms)
  Rendered call_histories/_index_core.html.haml (2617.2ms)
  Rendered call_histories/index.html.haml within layouts/application (2618.4ms)
  Rendered shared/_header.de.html.haml (200.0ms)
  Rendered shared/_system_message.html.haml (1.3ms)
  Rendered shared/_flash.html.haml (0.1ms)
Completed 200 OK in 3075ms (Views: 2803.8ms | ActiveRecord: 51.9ms)

Started GET "/sip_accounts/4/call_histories?type=dialed" for a.b.c.d at 2012-12-21 10:55:03 +0100
Processing by CallHistoriesController#index as HTML
  Parameters: {"type"=>"dialed", "sip_account_id"=>"4"}
  Rendered call_histories/_navigation.html.haml (4.2ms)
  Rendered call_histories/_navigation.html.haml (2.9ms)
  Rendered call_histories/_index_core.html.haml (5902.3ms)
  Rendered call_histories/index.html.haml within layouts/application (5903.7ms)
  Rendered shared/_header.de.html.haml (9.0ms)
  Rendered shared/_system_message.html.haml (1.2ms)
  Rendered shared/_flash.html.haml (0.1ms)
Completed 200 OK in 5982ms (Views: 5842.8ms | ActiveRecord: 82.5ms)

Started GET "/sip_accounts/4/call_histories?type=forwarded" for a.b.c.d at 2012-12-21 10:55:12 +0100
Processing by CallHistoriesController#index as HTML
  Parameters: {"type"=>"forwarded", "sip_account_id"=>"4"}
  Rendered call_histories/_navigation.html.haml (1.6ms)
  Rendered call_histories/_navigation.html.haml (0.7ms)
  Rendered call_histories/_index_core.html.haml (923.1ms)
  Rendered call_histories/index.html.haml within layouts/application (924.2ms)
  Rendered shared/_header.de.html.haml (8.5ms)
  Rendered shared/_system_message.html.haml (1.2ms)
  Rendered shared/_flash.html.haml (0.1ms)
Completed 200 OK in 990ms (Views: 932.9ms | ActiveRecord: 12.5ms)

**Comment by wintermeyer** [comment]
Added caching with 0d5fd7ba5092b4d00826f3572448bb54ac2ec983
