### ISSUE TITLE
löschen einer Rufnummer

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#243]
URL which triggered the bugreport is: /sip_accounts/22/phone_numbers
GS5 buildname: 1303130517-develop (5.1.2-develop)

Please provide your bugreport below this line and update the title of this issue to a more specific one.

ActiveRecord::RecordNotFound at /sip_accounts/22/phone_numbers/50
Couldn't find PhoneNumber with id=50 [WHERE `phone_numbers`.`state` = 'active' AND `phone_numbers`.`phone_numberable_id` = 22 AND `phone_numbers`.`phone_numberable_type` = 'SipAccount']

Die Rufnummer ist nach einem Reload trotzdem weg.

**Comment by wintermeyer** [comment]
Can you reproduce the error?

**Comment by getsolveit** [comment]
Yes, I do.

**Comment by wintermeyer** [comment]
Please provide us with a step by step walkthrough. What did you do to replicate the problem? Screenshots could be helpful.

**Comment by getsolveit** [comment]
![error1](https://f.cloud.github.com/assets/3115028/258160/952f411c-8c8b-11e2-8987-ba7515aca588.jpg)

Dann kommt ZWEI mal die Abfrage, ob man die Rufnummer löschen möchte!

**Comment by getsolveit** [comment]
![error2](https://f.cloud.github.com/assets/3115028/258165/b529adfe-8c8b-11e2-82b5-867b3bc3044e.jpg)

Die Nummer ist dann weg.

**Comment by spag** [comment]
Could not replicated this issue using build #1303200520-develop.

**Comment by getsolveit** [comment]
I have run gs-update and test it again and have the same issue.

**Comment by spag** [comment]
@getsolveit Could you please test it with a current development ISO in live mode?

**Comment by getsolveit** [comment]
Sthe same issue with the current development ISO.
![delete_phonenumbers](https://f.cloud.github.com/assets/3115028/473686/89379ff0-b754-11e2-9000-c0457bb5b257.png)

**Comment by getsolveit** [comment]
Ich glaube das ist gar kein Problem vom Rufnummern löschen sondern allgemein ein Problem, wenn Datensätze gelöscht werden sollen. Es wird der IE10 eingesetzt.

**Comment by spag** [comment]
Could it be an IE10 specific issue then?

**Comment by spag** [comment]
Closed for for inactivity. Please feel free to reopen if this issue still exists.
