### ISSUE TITLE
Conference member cannot be added with different numbers from phonebook

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#247]
I have a phonebook entry for somebody with at least 2 numbers (1x mobile, 1x landline/internal).
I can add the mobile number as a member to a conference. If I try to add the second number (the internal one) I get the error "Es wurden Validierungsfehler bei Ihren Eingaben gefunden."

**Comment by spag** [comment]
fixed in commit 706ffe50d3bb6270682783acc1e7817e8f7cf0f6
