### ISSUE TITLE
CLIR flag is not respected in dialplan

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#258]
URL which triggered the bugreport is: /call_routes/34/route_elements
GS5 buildname: 1302281156 (5.1.1)

I set the CLIR flag to true for a SIP account but it seems it's been ignored since the log still says:

```
013-03-15 17:25:04.145235 [INFO] switch_cpp.cpp:1274 ### [7792c34a-daab-484f-85ee-7fbfd49e990f] CALLER_ID_NUMBERS - clir: false, numbers: +4989xxxx,xx
```

**Comment by spag** [comment]
fixed in commit 1702b51b05ca73751bd52c715dd453f98d9b578f
