### ISSUE TITLE
Feature request: phonebook lookup on external call to hunt group

### ISSUE THREAD

**Issue by stefbw** [amooma/GS5#259]
When an external call is mapped to a hunt group (strategy: all), only the hunt group name and the caller id are shown, but not the caller name from the phone book. It would be nice, if the caller name could be displayed on the phones.

**Comment by stefbw** [comment]
Thanx for assigning. Earlier isn't possible? :-)

Anyway: what do you estimate, is this a lot of work and complicated? I am thinking of trying to develop myself ... could you estimate what time an experienced Gemeinschaft-developer would need? Then I could convert that into a time for a newbie (as a Gemeinschaft-developer).

**Comment by wintermeyer** [comment]
@stefbw 2-3 days. Testing this stuff is a bitch.

I close this issue now. Please contact us in case you need it done and are willing to pay for the work.

**Comment by stefbw** [comment]
Ok. I thought this was an issue tracker for the community, not only amooma. Seems I got it wrong.
