### ISSUE TITLE
Voicemailbox

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#262]
URL which triggered the bugreport is: /sip_accounts/1/voicemail_messages
GS5 buildname: 1303190445-develop (5.1.2-develop)

Please provide your bugreport below this line and update the title of this issue to a more specific one.

Es ist nicht möglich, wenn man die Voicebox anruft, die Nachricht abzuhören, es wird zwar Datum und Uhrzeit angesagt, aber dann springt die Box wieder an den Anfang und man kann mit 1 die neuen Nachrichten abhören, dann wieder Datum und Uhrzeit, aber keine Nachricht.

**Comment by jpawlowski** [comment]
Was sagt das FS log während der Session?

**Comment by jpawlowski** [comment]
module say_de seems to have changes which the german voice files currently do not reflect.

```
fs_cli sagt "error opening file /opt/freeswitch/sounds/de/tts/google/digit/h-5_m.wav
System Error no such file or directory.
```

I need to go deeper into this...

also see
https://groups.google.com/forum/?fromgroups=#!topic/gs5-users/zwPJKvif1Ro

**Comment by jpawlowski** [comment]
Open FS JIRA tickets regarding this topic:
http://jira.freeswitch.org/browse/FS-4722#comment-40572
http://jira.freeswitch.org/browse/FS-5275

**Comment by jpawlowski** [comment]
fixed by
https://github.com/amooma/GBE-system/commit/6dadbbd71457142fc34a3e86277c71c65c4a6330
https://github.com/jpawlowski/freeswitch-sounds-tts/commit/8d10d47a7e7e3d50c417b90403bd34d4d6815067
