### ISSUE TITLE
Anlegen von BLF über GUI

### ISSUE THREAD

**Issue by lfroehlich** [amooma/GS5#264]
URL which triggered the bugreport is: /sip_accounts/5/softkeys
GS5 buildname: 1303200520-develop (5.1.2-develop)

Beim Anlegen eines BLF kommt, auch bei Eingabe einer Nummer, ein Validierungsfehler. Das Feld "Nummer" muss ausgefüllt werden. Das BLF wird nicht angelegt.

**Comment by spag** [comment]
Hat die Gruppe der der Account angehoert (oder User/Tenant) die Berechtigtung "pickup" und "presence" fuer eine Gruppe der der entsprechenden Ziel-Account angehoert?

http://127.0.0.1/groups

**Comment by spag** [comment]
Fixed in commit 12dc5e76ea0499f7f3e7ff67a37d77e0e9d35e5e
