### ISSUE TITLE
haproxy breaks ability to use SSO in apache

### ISSUE THREAD

**Issue by duebel-** [amooma/GS5#268]
when haproxy is seated in front of apache2 like in the current builds SSO against AD does not work anymore.

**Comment by duebel-** [comment]
Drop haproxy.

Use mod_proxy for URIs with local part starting with /faye.*

**Comment by jpawlowski** [comment]
Nope, mod_proxy is not sufficient for using real websockets. Apache is not able to handle it appropriately (not even nginx is able to really handle it).

SSO should not have a problem, the only part that needs adaption is the client IP source related part in the Apache configuration. Either it needs to use the X-Forwarded-For header to get the clients actual IP address or we need to go for the user agent (which I would prefer as I always wanted to get rid of the network environment specific IP part).

**Comment by duebel-** [comment]
I digged into haproxy a bit further...

Please unset option http-server-close in defaults. Then SSO does work again.

**Comment by jpawlowski** [comment]
This might not be a good idea for websocket requests:
http://blog.silverbucket.net/post/31927044856/3-ways-to-configure-haproxy-for-websockets

But lets try if it's okay to shift this setting to the faye section instead of using this a default.

**Comment by jpawlowski** [comment]
https://github.com/amooma/GBE-system/commit/445e474b06195705dd7847274620ab395dfd61e4
