### ISSUE TITLE
Duplicate announcements in confernece

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#271]
joining a confcall announcement "you are currently the only person" is played twice.

**Comment by spag** [comment]
I'm unable to replicate this problem.

**Comment by jpawlowski** [comment]
Same here.
Its actually not a new issue, i see this already since version 5.0.
If you cant replicate both i will make a record and send logs after i
return from my trip

Sent from my iPad

On 27.03.2013, at 15:55, spag notifications@github.com wrote:

I'm unable to replicate this problem.

—
Reply to this email directly or view it on
GitHubhttps://github.com/amooma/GS5/issues/271#issuecomment-15528073
.

**Comment by spag** [comment]
> Its actually not a new issue, i see this already since version 5.0.

Are you sure this error is still present in the newer builds? I've created a whole new conference class about one week ago.

**Comment by jpawlowski** [comment]
These issues are valid for 5.1.2-master. I will check from develop later on

On 27.03.2013, at 17:17, spag notifications@github.com wrote:

Its actually not a new issue, i see this already since version 5.0.

Are you sure this error is still present in the newer builds? I've created
a whole new conference class about one week ago.

—
Reply to this email directly or view it on
GitHubhttps://github.com/amooma/GS5/issues/271#issuecomment-15533425
.

**Comment by jpawlowski** [comment]
I just created a logfile for you:
https://gist.github.com/jpawlowski/bb2f39c272cc6b812766

Records of two sessions (2nd should match with the log):
https://dl.dropbox.com/u/159727/call%20recording%20with%2080%3A07.04.2013%2014%3A09%3A18.wav
https://dl.dropbox.com/u/159727/call%20recording%20with%2080%3A07.04.2013%2014%3A12%3A21.wav

**Comment by spag** [comment]
Which GS5 Version has been involved?

**Comment by jpawlowski** [comment]
5.1.2 is affected.

**Comment by spag** [comment]
Can you please test it with a new development build? I'm unable to replicate it here.

**Comment by jpawlowski** [comment]
seems this issue does not occur anymore in current dev images.
