### ISSUE TITLE
Overlapping announcements when last participant leaves confcall

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#272]
announcement "username has left the conference" and "you are currently the only person in this conference" get overlapped if there are only 2 participants in a confcall and one of them leaves.

**Comment by spag** [comment]
I'm unable to replicate this.

**Comment by jpawlowski** [comment]
You may call my confcall using two devices if you want ;-)

On 27.03.2013, at 15:54, spag notifications@github.com wrote:

I'm unable to replicate this.

—
Reply to this email directly or view it on
GitHubhttps://github.com/amooma/GS5/issues/272#issuecomment-15527947
.

**Comment by jpawlowski** [comment]
must be related to #271 which I just updated with more information

**Comment by jpawlowski** [comment]
seems this issue does not occur anymore in current dev images.
