### ISSUE TITLE
Tastenfunktionen Rufumleitung fehlt.

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#277]
URL which triggered the bugreport is: /sip_accounts/4/softkeys/5/edit
GS5 buildname: 1303130517-develop (5.1.2-develop)

Please provide your bugreport below this line and update the title of this issue to a more specific one.

Version ist vom 02.04.2013.

Im Dropdownmenü fehlt die Möglichkeit die Taste als Rufumleitung zu deklarieren.

**Comment by getsolveit** [comment]
Wenn man eine Rufumleitung nur für den Sipaccount eingerichtet hat, fehlt die Funktion. Wenn es eine Umleitung für eine Rufnummer gibt, funktioniert es.

**Comment by spag** [comment]
Can't replicate it with any newer development build.
