### ISSUE TITLE
Tastenfunktionen Besetzt-Lampe

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#278]
URL which triggered the bugreport is: /sip_accounts/4/softkeys/1/edit
GS5 buildname: 1303130517-develop (5.1.2-develop)

Wenn man aus der Dropdownbox Besetzt-Lampe auswählt und bei Nummer etwas einträgt, gibt's einen Fehler.

Es wurden Validierungsfehler bei Ihren Eingaben gefunden.

Nummer ........ muss ausgefüllt werden, aber es gibt die Nummer und es stand ja auch etwas in dem Feld.

**Comment by spag** [comment]
Hat die Gruppe der SIP-Accounts die noetlge "presence" Berechtigung?

**Comment by getsolveit** [comment]
Ich habe mal in die GUI-Funktionen geschaut, da hab ich nichts gefunden, wo versteckt sich die Berechtigung?

**Comment by spag** [comment]
http://"ip_address"/groups

**Comment by getsolveit** [comment]
Es gibt folgende Einträge:

Name Permissions Memberships Comment

  admins 0  0 Administrator user accounts   Anzeigen     Bearbeiten     Löschen  
  users 0  2 Generic user accounts   Anzeigen     Bearbeiten     Löschen  
  tenant_sip_accounts 0  0 SIP accounts owned by tenants   Anzeigen     Bearbeiten     Löschen  
  user_sip_accounts pickup  90 SIP accounts owned by user accounts   Anzeigen     Bearbeiten     Löschen  
  international_calls 0  90 International calls permitted   Anzeigen     Bearbeiten     Löschen  
  national_calls 0  90 National calls permitted 

Finde nichts mit presence.

**Comment by spag** [comment]
Dann haben wir wahrscheinlich die Ursachen.
Man muss die "presence" Berechtigung z.B. zur gruppe "user_sip_accounts" hinzufuegen, sonst erlaubt das System nicht die Ueberwachung eines SIP Accounts und damit auch keine BLF Taste.

**Comment by getsolveit** [comment]
Klappt!
