### ISSUE TITLE
Datei-Upload schlägt fehl

### ISSUE THREAD

**Issue by ckgth** [amooma/GS5#281]
Der Upload einer Ansage (greeting) oder andere Art von Dateien läuft, jedoch kommt eine Fehlermeldung nach Hochladen im GUI.
Dies im Hauptuser und untergeordneten Usern. 

Version: 5.1.3-develop #1304200448rpi-develop

**Comment by jpawlowski** [comment]
Die Entwicklerversion erhebt keinen Anspruch darauf bereits Feature-Complete zu sein.
Bugreports dieser Art machen nur bei einer Beta Sinn.
