### ISSUE TITLE
Update von 5.1-beta8 (sudo gs-update) schlägt fehl.

### ISSUE THREAD

**Issue by pospinr1** [amooma/GS5#282]
Risk accepted.

error: Failed connect to github.com:443; Connection refused while accessing https://github.com/amooma/GBE-system.git/info/refs

Wo werden die Zugangsdaten für die github-Anmeldung gesetzt ? Oder stimmt der URL nicht ?

**Comment by jpawlowski** [comment]
Es wird vermutlich eher ein Fehler mit deiner Internetverbindung sein.
