### ISSUE TITLE
Bugreport: Anzeigen Backup führt zu Fehler ...

### ISSUE THREAD

**Issue by pospinr1** [amooma/GS5#283]
URL which triggered the bugreport is: /backup_jobs
GS5 buildname: 1303251159 (5.1.2)

Please provide your bugreport below this line and update the title of this issue to a more specific one.

We're sorry, but something went wrong.

Please take a minute and report an issue at https://github.com/amooma/GS5/issues or contact your admin.

... Beim Klicken auf den Anzeigen-Button des ersten (und einzigen) Eintrags.

**Comment by jpawlowski** [comment]
doubles #279
