### ISSUE TITLE
Sort links do not work

### ISSUE THREAD

**Issue by duebel-** [amooma/GS5#286]
/tenants/2/users?sort=first_name etc. does not affect the display order of users. It always the order of creation.

See #240 and #285

**Comment by duebel-** [comment]
This is a caching issue.

After restarting memcached and reloading the page /tenants/2/users?sort=first_name the sorting is done once. Then the page is always sorted in that initial sorting order.

**Comment by spag** [comment]
fixed in commit ef07898499292b72ce011bc9f3494cb4dade1d6b
