### ISSUE TITLE
Add Softkey does not work

### ISSUE THREAD

**Issue by d-mark** [amooma/GS5#287]
I tried to add a softkey on a GS5.1.2 but I only got a "We're sorry...".
Message from "production.log.2":

```
NoMethodError (undefined method `hunt_group' for nil:NilClass):
  app/models/softkey.rb:35:in `block in possible_call_forwards'
  app/models/softkey.rb:34:in `possible_call_forwards'
  app/controllers/softkeys_controller.rb:55:in `set_available_softkey_functions'
```

**Comment by getsolveit** [comment]
Was ist hiermit gemeint? Die Tasten am Telefon? Z.B. Snom? Das funktioniert ohne Probleme.

**Comment by d-mark** [comment]
In der Weboberfläche unter SIP-Account -> Tastenbelegungen -> +Neuer Softkey , danach kommt direkt ein "We're sorry, but something went wrong.". Zugehörige Meldung des Production.log siehe oben.

Telefone sind Snom 370/320.

Da etwas von "hunt_group" in der Meldung steht: Es gibt auf der Anlage eine Hunt Group, welche auch eine Rufweiterleitung nach 15 Sekunden hat.

**Comment by getsolveit** [comment]
Okay, ich habe das Problem mit der aktuellen Devel nicht, scheint wohl behoben zu sein.

**Comment by spag** [comment]
Bitte wieder eroeffnen, falls das Problem in der aktuellen Development version weiter auftritt.
