### ISSUE TITLE
Deleting HuntGroup does not work

### ISSUE THREAD

**Issue by mades5** [amooma/GS5#288]
NameError (uninitialized constant HuntGroup::DestrinationCallForward):
  app/controllers/hunt_groups_controller.rb:44:in `destroy'

5.1.2 Build #1303251159, Rails 3.2.13

**Comment by mades5** [comment]
1.9.3-p392 :002 > HuntGroup.find(1).destroy
  HuntGroup Load (0.1ms)  SELECT `hunt_groups`.\* FROM `hunt_groups` WHERE `hunt_groups`.`id` = 1 LIMIT 1
   (0.0ms)  BEGIN
   (0.2ms)  ROLLBACK
NameError: uninitialized constant HuntGroup::DestrinationCallForward
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/inheritance.rb:111:in `compute_type'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/reflection.rb:172:in`klass'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/associations/association.rb:117:in `klass'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/associations/association.rb:165:in`find_target?'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/associations/collection_association.rb:334:in `load_target'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/associations/collection_proxy.rb:44:in`load_target'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/associations/collection_proxy.rb:87:in `method_missing'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/associations/builder/has_many.rb:32:in`block in define_destroy_dependency_method'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:407:in `_run__454054310__destroy__673090057__callbacks'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in`__run_callback'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_destroy_callbacks'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in`run_callbacks'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/callbacks.rb:254:in `destroy'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/transactions.rb:254:in`block in destroy'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in`transaction'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/transactions.rb:208:in `transaction'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/transactions.rb:311:in`with_transaction_returning_status'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.13/lib/active_record/transactions.rb:254:in `destroy'
    from (irb):2
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in`start'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.13/lib/rails/commands.rb:41:in`<top (required)>'
    from script/rails:67:in `require'

**Comment by mades5** [comment]
+----+-----------+------+----------+-----------------------+---------------------------+---------------------------+------------+---------------------+--------------------------------------+
| id | tenant_id | name | strategy | seconds_between_jumps | created_at                | updated_at                | gs_node_id | gs_node_original_id | uuid                                 |
+----+-----------+------+----------+-----------------------+---------------------------+---------------------------+------------+---------------------+--------------------------------------+
| 1  | 2         | test | ring_all |                       | 2013-03-29 23:01:10 +0100 | 2013-05-13 03:33:42 +0200 | 1          |                     | 16890b70-7aea-0130-4663-080027c17cf4 |
+----+-----------+------+----------+-----------------------+---------------------------+---------------------------+------------+---------------------+--------------------------------------+
1 row in set

**Comment by duebel-** [comment]
Same here, cannot delete hunt group in UI.

**Comment by spag** [comment]
fixed in commit 3def6156141c1235d1ab0782900d43c097676243
