### ISSUE TITLE
Anruflisten löschen

### ISSUE THREAD

**Issue by DieterSpeiser** [amooma/GS5#291]
Anruflisten Gesamt-Löschung!
Es ist sehr mühsam die einzelnen Anrufe in der Anrufliste zu löschen,daher wäre es schön wenn man die Listen mit einem Klick löschen könnte.
Noch besser, man könnte vom Telefon aus die Listen löschen,so wie in GS3.1.
Vielleicht kann man das als Feature Request aufnehmen .

**Comment by duebel-** [comment]
see #18

**Comment by jpawlowski** [comment]
duplicate
