### ISSUE TITLE
Missing pagination links

### ISSUE THREAD

**Issue by duebel-** [amooma/GS5#293]
URL which triggered the bugreport is: /tenants/2/sip_accounts

no pagination links are displayed

**Comment by wintermeyer** [comment]
Welche Links genau? Ich verstehe die Beschreibung nicht.

**Comment by duebel-** [comment]
page with DEFAULT_PAGINATION_ENTRIES_PER_PAGE > # sip_accounts:

![image](https://f.cloud.github.com/assets/3012245/689907/647b1952-dac3-11e2-8568-de0cb8fab403.png)

page with DEFAULT_PAGINATION_ENTRIES_PER_PAGE < # sip_accounts => no links for further pages:

![image](https://f.cloud.github.com/assets/3012245/689896/060996aa-dac3-11e2-96f0-fbf55b706bb5.png)

**Comment by duebel-** [comment]
The same issue applies to /tenants/2/phones.

**Comment by spag** [comment]
Sorry, I'm unable to replicate this issue.
The pagination links appear as soon as DEFAULT_PAGINATION_ENTRIES_PER_PAGE is reached.
Please reopen if this issue can be replicated in the newest build.
