### ISSUE TITLE
Redial directory on the phone is slow

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#294]
I guess the XML rendering has to be optimized and maybe cached. 

CC @duebel-

**Comment by duebel-** [comment]
URI /config_snom/6/3/call_history.xml?type=dialed

**Comment by duebel-** [comment]
/config_snom/6/3/call_history.xml?type=missed
and
/config_snom/491/3/call_history.xml?type=received

are affected, too.

**Comment by spag** [comment]
Added caching in commit 2277451c220ffb45aefae2a1bbd3a37821fa5dd8

**Comment by duebel-** [comment]
Please reopen.

app/views/config_snom/_snom_phone_directory.xml.haml != app/views/config_snom/call_history.xml.haml

**Comment by spag** [comment]
cat app/views/config_snom/call_history.xml.haml

!!! XML
= render @phone_xml_object[:name]
