### ISSUE TITLE
GS5 on beaglebone black possible ?

### ISSUE THREAD

**Issue by MSTKMSTK** [amooma/GS5#302]
Hallo,
Wird es von Gemeinschaft auch eine Version für den "Beaglebone black" geben?
Das könnte evtl. Vorteile bringen da zusätzlich 2 GB eMMC onboard ist ( Lese- / Schreibgeschwindigkeit / Lebensdauer ) und die CPU mit 1GHz auch mehr Performance bringt. Anscheinend für 24/7 auch stabiler als das RasPI...
Gruß Michael

**Comment by wintermeyer** [comment]
Bitte diese Frage auf der Mailingliste stellen.

**Comment by artzde** [comment]
hallo ich habe die gleiche Frage. Auf einem EEE-PC habe ich die Installation nicht hinbekommen in einer virtuellen Maschine VirtualBox. Ich hätte da auch einen Beaglebone frei. Um welche  Mailingliste handelt es sich und wo kann man sich eintragen zum anfragen. es sind ja schon8 Monate vergangen seit der Anfrage.

**Comment by saschadaniels** [comment]
https://groups.google.com/forum/#!forum/gs5-users
