### ISSUE TITLE
Huntgroup deletion fails (GS5.1)

### ISSUE THREAD

**Issue by fwtag** [amooma/GS5#304]
Huntgroups can't be deleted. No matter if they are empty (no members, phone numbers, etc.) or not.

**Comment by wintermeyer** [comment]
Please attach a screenshot of the error message.

**Comment by fwtag** [comment]
![bildschirmfoto 2013-07-13 um 19 07 14](https://f.cloud.github.com/assets/4759292/793098/bbbc565a-ebde-11e2-9a9c-34eba92376d7.png)

**Comment by wintermeyer** [comment]
Please attach a screenshot of the page where you try to delete the Huntgroup. Hint: Always use the link on the bottom of the GS5 page to send bug reports.

**Comment by fwtag** [comment]
URL which triggered the bugreport is: /tenants/2
GS5 buildname: 1303251159 (5.1.2)

Please provide your bugreport below this line and update the title of this issue to a more specific one.

![bildschirmfoto 2013-07-13 um 19 43 51](https://f.cloud.github.com/assets/4759292/793144/40c022c8-ebe4-11e2-949c-6f1ee2d79117.png)

**Comment by duebel-** [comment]
Duplicate issue, see #288.

**Comment by jpawlowski** [comment]
close as a duplicate
