### ISSUE TITLE
Problem in router.lua:147 in special routing cases

### ISSUE THREAD

**Issue by ip6li** [amooma/GS5#305]
Enclosed config yields to following error if other user than 593 try to send a fax:

2013-07-14 10:30:07.751723 [ERR] mod_lua.cpp:200 /usr/share/freeswitch/scripts/dialplan/router.lua:147: attempt to call method 'to_s' (a nil value)
stack traceback:
    /usr/share/freeswitch/scripts/dialplan/router.lua:147: in function 'route_match'
    /usr/share/freeswitch/scripts/dialplan/router.lua:200: in function 'route_run'
    /usr/share/freeswitch/scripts/send_fax.lua:113: in main chunk

![bildschirmfoto vom 2013-07-14 10 35 02](https://f.cloud.github.com/assets/3518041/794024/a807a9ac-ec60-11e2-888b-20d782dec514.png)

I think this is a valid routing entry, if user 593 set up a call from phone, that route does exactly what it should do.

**Comment by spag** [comment]
Does this error occur in any of the recent development builds?

**Comment by spag** [comment]
Please reopen if still present in 5.2.x
