### ISSUE TITLE
Can not install with manual partitioning

### ISSUE THREAD

**Issue by BUGHUNTER** [amooma/GS5#33]
Trying to install I would like to use manual partitioning - this leads to an error:

"No root filesystem" (see attached screenshot).

The partitioner is called after this, but jumps immediately to the same screen and is stuck in a loop. 

![AMOOMA_GS5_NO_ROOT_PARTITION_FAIL](https://f.cloud.github.com/assets/1013014/32842/d9f3ced6-5049-11e2-8d00-b9fe49ef23ff.PNG)

**Comment by jpawlowski** [comment]
Manual partitioning is currently not supported as we see GS5 as an appliance which should not be used for other purpose.

**Comment by Maesto** [comment]
Is there a workaround? I normally put /boot on its on harddrive. (KVM) This way I can resize the VM storage without any problems.

**Comment by jpawlowski** [comment]
I fear there is currently no workaround.
