### ISSUE TITLE
problems when creating an admin account - fresh installation

### ISSUE THREAD

**Issue by tholli** [amooma/GS5#38]
After creating a new server (fresh installation) via http://localhost/gemeinschaft_setups/new with filling out any needed forms following error occurs:

**\* snip
Errno::ENOENT (No such file or directory - /nonexistent/.ruby-uuid):
  lib/activerecord_extensions.rb:10:in `new'
  lib/activerecord_extensions.rb:10:in`populate_uuid'
  app/controllers/gemeinschaft_setups_controller.rb:22:in `create'

cache: [POST /gemeinschaft_setups] invalidate, pass
**\* snap

uuid-2.3.6 is defintely installed. How can I solve this issue?

**Comment by wintermeyer** [comment]
Please use the ISO image. The source code is for development only.
