### ISSUE TITLE
Backup and Restore functionality

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#39]

**Comment by saschadaniels** [comment]
Ich fand das Backup to yaml ziemlich gelungen. Eine Kombination mit 
einen tgz der restlichen lokalen files wäre relativ leicht machbar.

Am 30. Dezember 2012 11:27:40 schrieb Stefan Wintermeyer 
notifications@github.com:

**Comment by jpawlowski** [comment]
Welche Anforderungen werden hier an die GBE gestellt?
Oder wird es einfach dann bei der Init-Seite die Möglichkeit geben eine vorhandene Config einfach hochzuladen?
Wie geht ihr mit Änderungen in den Textdateien um?

**Comment by wintermeyer** [comment]
Ich weiß selber noch nicht, was alles in ein Backup rein muss. Ich weiß auch nicht, wie wir das im UI abbilden können.

@spag Hast Du eine Liste mit Konfigurationsdateien, die wir auf jeden Fall sichern müssen?

**Comment by saschadaniels** [comment]
Am 30.12.2012 12:25, schrieb Stefan Wintermeyer:

> Ich weiß selber noch nicht, was alles in ein Backup rein muss. Ich weiß
> auch nicht, wie wir das im UI abbilden können.
> 
> @spag https://github.com/spag Hast Du eine Liste mit
> Konfigurationsdateien, die wir auf jeden Fall sichern müssen?

Wir könnten alle lokalen Dateien (inkl. db/database.yaml) nach
/opt/gemeinschaft-local legen und verlinken.

Das funktioniert auch bei der 3 sehr gut und man kann "git pull"
gefahrlos machen.

Wenn man db/ auch noch dort hin legt kann man das yaml backup machen und
dann ein tgz von /opt/gemeinschaft-local zum Download bereit stellen.

**Comment by jpawlowski** [comment]
Könnten wir, um sie zentral zu haben, ja.
Ich würde trotzdem Symlinks aus /etc/gemeinschaft/ und anderen Systempfaden erzeugen, damit diese auch an den richtigen Stellen, wo man es per Default erwartet, gefunden werden können.

**Comment by saschadaniels** [comment]
Am 30.12.2012 22:07, schrieb Julian Pawlowski:

> Könnten wir, um sie zentral zu haben, ja.
> Ich würde trotzdem Symlinks aus /etc/gemeinschaft/ und anderen
> Systempfaden erzeugen, damit diese auch an den richtigen Stellen, wo man
> es per Default erwartet, gefunden werden können.

So war das auch gemeinst, hatte ich nur vergessen zu schreiben. Sorry!

**Comment by wintermeyer** [comment]
Mental note: Duplicate the MySQL database. Delete the contente of fax and voicemail tables (without deleting the table itself). Do the backup. Change the database name in the dump.

**Comment by wintermeyer** [comment]
Mental note: https://github.com/meskyanichi/backup

**Comment by jpawlowski** [comment]
Kann man das Ruby-Script dann auch von der Console aus verwenden, z.B. um automatisiert Backups auf einen externen Server auszulagern? Ansonsten würde ich sowas noch als Shellscript bauen. Muss ja aber nicht doppelt gemoppelt werden.

Die GBE ist soweit darauf eingestellt, dass nur die DB und das Verzeichnis /var/opt/gemeinschaft gebackupt und wiederhergestellt werden müssen.
GBE unterstützt es auch, dass Tasks wie db:migrate, die Installation neu hinzugekommener Gems (halt das was bundle install macht) und das Setzen der korrekten Zugriffsrechte durchgeführt wird. All das passier während des Boot-Vorgangs und wird derzeit dadurch ausgelöst, das ein (neuerer) GS5-Git-Clone in /opt/GS5.update gefunden wird.

Ich weiß noch nicht was ich daran noch anpassen muss/sollte, wenn das Web-Backup funktioniert. Die Dateirechte werden derzeit auch bei jedem normalen Start forciert, ein Reboot würde also ggf ausreichen. Allerdings habe ich die Funktion auch über das neue Config-File /etc/gemeinschaft/system.conf abschaltbar gemacht, um bei langsamen Systemen eine Performance-Stellschraube für den Boot zu haben.

**Comment by wintermeyer** [comment]
Done.
