### ISSUE TITLE
Installation auf  Igel-4210 LX

### ISSUE THREAD

**Issue by gesicmerrybeard** [amooma/GS5#42]
Bein Versuch GS5 auf  einem Igel-4210 LX Thin Client zu installieren kommt es zu diversen Problemen.
U. A. reichen die eingebauten 1GB Ram scheinbar nicht und die Datenbanken zu migrieren.
Ich habe die Installation über 10 Stunden laufen lassen und sie konnte scheinbar trotzdem nicht alle Scripte der Installation erfolgreich abarbeiten. Es werden immer wieder Prozesse geschlossen um Speicher frei zu machen unter anderem apache, mysql und ruby.

Nach den 10 Stunden habe ich folgende Fehler angezeigt bekommen.
![2012-12-30 14 25 22](https://f.cloud.github.com/assets/2207752/35907/4c983912-5294-11e2-990a-8a032a3f5ad0.jpg)

Darauf hin habe ich den Thin Client neu gebootet und es kam zur erneuten Ersteinrichtung durch die Scripts welche folgende Fehler ergaben.

![2012-12-30 16 06 48](https://f.cloud.github.com/assets/2207752/35910/a22896d8-5294-11e2-85db-b9c46d62d7f1.jpg)
![2012-12-30 16 10 08](https://f.cloud.github.com/assets/2207752/35912/ce6c892a-5294-11e2-8f09-8859ae64212d.jpg)

Beim "Execute db:migrate" scheint der Thin Client nun wieder aufgrund von Speichermangel zu hängen.

Wenn weitere Daten wie z. B. betimmte log-Dateien benötigte werden bitte nachfragen.

**Comment by wintermeyer** [comment]
Wie viel Festplattenplatz hat das System? Was für eine CPU ist eingebaut?

**Comment by wintermeyer** [comment]
BTW: 1 GB RAM reicht. Ich teste immer mit 512 MB.

**Comment by gesicmerrybeard** [comment]
VIA C7 CPU 1 GHz und 8GB über CF Karte http://www.amazon.de/gp/product/B000W05O5O/ref=oh_details_o04_s00_i00

Hatte darauf auch schon Debian mit Asterisk / Apache sowie Debian mit GS3 zum Laufen gebracht ohne Modifikationen vornehmen zu müssen.

Lediglich bei der Installation von GS5 kommt es zu diesen Problemen.
Ich habe nun auch schon 3 mal die Installation neu gestartet. Mit 3 verschiedenen Instllationsmedien (1GB USB 2.0 Stick, 8GB USB 2.0 USB Stick und 500GB USB 3.0 Festplatte, jedesmal habe ich die ISO neu herunter geladen und mittels Image Writer auf das Medium übertragen.

**Comment by wintermeyer** [comment]
Ich befürchte es liegt am VIA C7. Vielleicht hat @jpawlowski noch eine Idee. Falls nicht, wird das auf dem VIA C7 nichts.

**Comment by gesicmerrybeard** [comment]
Inwiefern sollte es am VIA C7 liegen an der Leistung oder an der Kompatibilität? Immerhin hat es bei Asterisk und bei GS3 ja auch geklappt.

**Comment by wintermeyer** [comment]
Es kann ein Kompatibilitätsproblem sein. Die Leistung ist egal (man muss nur genug Geduld haben). Mal schauen, was @jpawlowski sagt.

**Comment by jpawlowski** [comment]
Ich hab leider auch keine direkte Idee dazu. Jedes Intel-basierte System sollte unterstützt werden.
Du kannst aber mal in /var/log/gemeinschaft/setup.log schauen, ob es da mehr details zu sehen gibt (ggf. die CF-Card mit einem anderen System entsprechend auslesen).

Die Systeminstallation ist ja grundsätzlich gelaufen, es hat also was mit rake zu tun. Ich weiß nicht ob der VIA Chip ggf. einige Befehle nicht unterstützt, vielleicht hilft es ruby/rails neu zu kompilieren.

Die Timezone-Information warnings können getrost ignoriert werden.

**Comment by gesicmerrybeard** [comment]
Hier mal das setup.log von heute Nachmittag 16:10.

Habe das ganze mal aufgrund der 577 Zeilen auf pastebin hochgeladen, http://pastebin.com/m0GzVQWw .

Das letze was im Log steht ist:
==  RemoveFaxDocumentableFromFaxDocuments: migrating ==========================

Ich werde gleich noch einmal eine Installation anstoßen und schauen ob es wieder am selbem Punkt stoppt.

**Comment by jpawlowski** [comment]
Danke. Zu den Ausgaben in /var/log/gemeinschaft/setup.log und /var/log/boot (der Teil ab "Initializing database") können @wintermeyer oder @spag mehr sagen.

**Comment by wintermeyer** [comment]
Bitte mit der Version 5.0.2 noch mal probieren (sollte morgen verfügbar sein). Wenn es damit nicht geht, dann sehe ich keine schnelle Lösung. 

Ich bin davon überzeugt, das GS5 auf dem C7 auch läuft. Aber wir haben keine Zeit den Installer entsprechend anzupassen. Für uns ist der C7 ein Nischenprodukt, das wir uns nur im Rahmen einen Consultingprojektes weiter anschauen würden.

**Comment by saschadaniels** [comment]
Ich würde versuchen die CF Card aus dem Thinclient in einem stärkeren Rechner mit Cardreader zu installieren und dann umstecken.

Am 30.12.2012 um 19:55 schrieb Stefan Wintermeyer notifications@github.com:
