### ISSUE TITLE
Md5 hash

### ISSUE THREAD

**Issue by gesicmerrybeard** [amooma/GS5#43]
Wäre es möglich auf der Webseite einen md5 hash zum Download veröffentlichen um sicher zu stellen das das Paket unverändert herunter geladen wurde?

**Comment by jpawlowski** [comment]
SHA1, SHA256 und MD5 Hashes gibt es, werden aktuell nur nicht verlinkt.

http://amooma.de/downloads/gs5/201212282253/MD5SUMS
http://amooma.de/downloads/gs5/201212282253/SHA1SUMS
http://amooma.de/downloads/gs5/201212282253/SHA256SUMS

Das Verzeichnis ändert sich freilich mit einem neuen Release entsprechend, die Dateinamen sind aber gleich.
