### ISSUE TITLE
Snoms (370/870) won't restart

### ISSUE THREAD

**Issue by TobiasW** [amooma/GS5#51]
Snoms won't restart after login/logout via feature code.
Logging in/out with the phone menu restarts the phone immediately.

**Comment by wintermeyer** [comment]
Which Firmware do you use?

**Comment by TobiasW** [comment]
Sorry I forgot, I tried it with 8.4.35

**Comment by wintermeyer** [comment]
Which GS version did you try?

**Comment by TobiasW** [comment]
5.0.1

**Comment by wintermeyer** [comment]
Please use tomorrow's nightly build. In case it doesn't solve the problem: Please reopen this ticket.

**Comment by TobiasW** [comment]
It's still not working with the latest nightly build

**Comment by wintermeyer** [comment]
@spag Do you have any ideas?

**Comment by spag** [comment]
Is a HTTP proxy involved in any way?

**Comment by TobiasW** [comment]
Nope, it's only my test lab network with GS in a vm and some snom phones

**Comment by Marcux83** [comment]
I have the same problem. Im using GS 5.0.2 (stable build), Snom 320@8.4.35. 
After Hot Desk Login/Out no reboot is performed

**Comment by spag** [comment]
fixed in commit d8ad6ffe483156ea5474e7c1874ea618d44ba306
