### ISSUE TITLE
GUI to set the maximum length and number of voicemails per user.

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#57]

**Comment by spag** [comment]
Hmm. What about making gs_parameters use the generic group subsystem? Groups can hold any object that can be identified by a class name and numeric ID - two attributes a gs_parameters entry clearly has.

**Comment by wintermeyer** [comment]
Sounds good.

**Comment by spag** [comment]
Can be set in gs_parameters (system wide) or in voicemail_settings (by voice mailbox).
Commit 1f8f054c6f6a8c968b1e6472480dbbdb6432bdd4
