### ISSUE TITLE
Transfer a current call into a stand by conference.

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#61]
Use case: I talk to A and want to have a three party conference call with A and B. But my SIP phone doesn't provide that functionality. So I need some sort of feature code to transfer my current call into a stand by conference.

@duebel- Please provide additional use cases in this issue in case I missed something here.

**Comment by spag** [comment]
What about using the "transfer all" function "f-ta-"?

e.g.

[prerouting]
^%_2%_(%d+)#$ , f-ta-%1

**Comment by duebel-** [comment]
Sounds promising...

f-ta transfers the caller and all callees to the new destination?

**Comment by spag** [comment]
Yes, that's exactly what it's intended for. But we still have to find out how reliable this method actually is.
