### ISSUE TITLE
Right management for Pickups.

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#65]
Currently anybody can pickup calls from anybody. That needs to be changed and needs to have some sort of right management.

all: Please provide ideas how to achieve this and what features would be nice.

**Comment by duebel-** [comment]
define some sort of pickup groups. pickup does only work inside of one group.

user1 and user2 are in pickupgroupA
user3 and user4 are in pickupgroupB

user1 can pick user2's calls but not the calls of user3 and user4 aso.

**Comment by spag** [comment]
Groups can be defined on the user level already but how to handle non-user SIP accounts (e.g. tenant accounts) then?

One could:
a) make groups universal (polymoprphic)
b) add a dedicated sip_account_groups Model

**Comment by wintermeyer** [comment]
Wouldn't be user level defined groups fine for the given problem? No need to add tenant accounts to this.

**Comment by spag** [comment]
I'm not 100% convinced no one needs this on tenant phones. In this stage it would't probably take much more effort to do it on the sip_account level.

**Comment by wintermeyer** [comment]
@spag Your call.

**Comment by spag** [comment]
implemented in commit 14facb5c1f50ae9edd0ac842001ab8e7afa52b21

**Comment by spag** [comment]
transitional permission check added in commit 1bcb85853b282606f28f1c9cd7f4e13d494a7290
