### ISSUE TITLE
Agent needs to be able to log in and out of a queue by a feature code and the WebGUI.

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#66]

**Comment by duebel-** [comment]
does work as softkey via /config_snom/11/4/acd.xml?acd=1&agent=1&function=toggle

feature code does work as f--acdmtg-AGENTID-ACDPHONENUMBER
would be better if -acdmtg-AGENTPHONENNUMBER-ACDPHONENUMBER worked.

**Comment by spag** [comment]
If ACDPHONENUMBER is provided, the AGENTID can bei set to "0" and vice versa.

**Comment by spag** [comment]
[prerouting]
^%_5%_(%d+)#$           , f-acdmtg-0-%1

**Comment by duebel-** [comment]
ok, works. feature code is fine then. :-)

**Comment by spag** [comment]
GUI part implemented in commit 4d7d5ad238990582d6c90a25272f2141ea9a3b28
