### ISSUE TITLE
Display phone number on idle screen

### ISSUE THREAD

**Issue by hehol** [amooma/GS5#67]
The user should be able to see his/her phone number in the idle screen of the phone display. Currently,  only the first name and last name are being shown.

Since a user can have more than one phone number, it may be a good idea to just show the phone number that has been configured first.

**Comment by wintermeyer** [comment]
We like the current behavior. But I see your point. There could be some sort of configuration parameter what to display. We have bigger fish to fry right now but I'll leave it as a feature request.

**Comment by spag** [comment]
Fixed in commit c5bfe11c01f2b3575ec96b6bd6f567976d93ff63
