### ISSUE TITLE
Let worker-job do notifications for fax and voicemail messages

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#7]
Currently there are two cronjobs for fax and voicemail notification emails running every minute.
It seems this is performance relevant as system usage shows higher load average.

As we have the worker-job running already (don't know what it's doing currently, but we have it), it should take care of sending email notifications.

Maybe also the regular logout_phone could be done by the worker-job making cronjobs completely obsolete.

**Comment by wintermeyer** [comment]
Mental note: https://github.com/bvandenbos/resque-scheduler might be a good solution.

**Comment by jpawlowski** [comment]
_tumbsup_

**Comment by spag** [comment]
added in commit 0f26298, See issue #127
