### ISSUE TITLE
U.S. ringback tone

### ISSUE THREAD

**Issue by hehol** [amooma/GS5#70]
When placing internal calls, a U.S. ringback tone is being played to the caller instead of a German ringback tone. If the PBX as a whole is German, the ringback tone should be as per ETSI recommendation (425 Hz for one second, 3-5 seconds of silence)

**Comment by spag** [comment]
The PBX defaults are not German and selecting "Germany" in the GUI doesn't affect the dialplan settings at the moment. 

You can set the ringback tone to anything you like in /opt/GS5/misc/freeswitch/scripts/ini/dialplan.ini

**Comment by wintermeyer** [comment]
@spag Most users don't know how to configure it. Please add the necessary configuration for German ringback tones in the /opt/GS5/misc/freeswitch/scripts/ini/dialplan.ini.
