### ISSUE TITLE
snom phone does not boot if user is being deleted

### ISSUE THREAD

**Issue by hehol** [amooma/GS5#71]
A user is logged on to a snom phone via hotdesking. If the user is being deleted via the web gui, the phone does not reboot. It shows the user's name until it is being rebooted manually.

**Comment by wintermeyer** [comment]
@spag Which method do I have to call to reboot all phones of a user? I'll add it as an after_destroy callback.

**Comment by spag** [comment]
I'm afraid you will have to use iteration to call "phone.resync" for all phones in the list.

**Comment by wintermeyer** [comment]
Fixed in b66cf13cab7bbef0ae4244aabc023fede67e36fb. Will be available in tomorrow's nightly build.
