### ISSUE TITLE
snom: attended transfer leaves call open at transferee

### ISSUE THREAD

**Issue by hehol** [amooma/GS5#72]
This is the scenario:
- user A calls user B
- user A presses the hold key
- user A calls user C
- user A presses the transfer key
- user A presses the enter key (red/white "tick" key)

Now, user B and user C are connected, but user A's phone still shows a call with user C but the line is "dead".

I'm using snom 370 and snom 821 with firmware 8.4.35.

**Comment by wintermeyer** [comment]
AFAIK this is a Snom Firmware problem.
