### ISSUE TITLE
provisioning_key = true als Default

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#73]
In phones/new den Wert für provisioning_key per Default auf true setzen.

**Comment by spag** [comment]
Besser PROVISIONING_KEY_LENGTH in GsParameter auf z.B. 12

**Comment by wintermeyer** [comment]
@spag Please double check ec342d3d91d2cfa8c210722354353cfe8a90a8bc and reopen the issue, in case something is still missing.
