### ISSUE TITLE
Let Lua scripts look for existing configuration in additional dir first

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#75]
Lus scripts in freeswitch/scripts currently load their configuration from /opt/gemeinschaft/misc/freeswitch/scripts/ini_.
As we have a local copy of those files now the scripts should check if the file is existing in /opt/gemeinschaft-local/freeswitch/scripts/ini/_ first and otherwise fallback to the original directory in the Git repo.

**Comment by spag** [comment]
The files look for configuration in /opt/GS5/misc/freeswitch/scripts/ini/ not in /opt/gemeinschaft/ - otherwise you would not be able to install GS3 and GS5 along each other.

**Comment by jpawlowski** [comment]
IMHO parallel installation is nothing one would do (anymore) with the appliance version we have now.
As we don't use the old install script anymore this change shouldn't be a problem.

As I would like to avoid adding GS5/misc/freeswitch/scripts/ini to .gitignore (the only way to keep "git-pull" working) I really would like to have this change. It's needed for our online-update approach @wintermeyer 

(oh and btw, /opt/GS5 is not the standard path anymore since my changes from last night).

**Comment by jpawlowski** [comment]
Conclusion from our confcall:
Peter is looking for a solution to get rid of those static ini files and Julian will make a rollback for /opt/GS5 to be the standard directory again.
