### ISSUE TITLE
phone book entries with German umlauts are not searchable in SNOM phone book

### ISSUE THREAD

**Issue by duebel-** [amooma/GS5#77]
GET "/config_snom/11/4/phone_book.xml?type=&keys=keys=685537" does not find "Müller"

Processing by ConfigSnomController#phone_book as XML
  Parameters: {"type"=>"", "keys"=>"keys=685537", "phone"=>"11", "sip_account"=>"4"}
  Rendered config_snom/_snom_phone_directory.xml.haml (1.8ms)

Either umlauts should be forbidden in phone book or '2' should stand for 'ä', '6' for 'ö' and so on...

**Comment by jpawlowski** [comment]
relates #53

**Comment by spag** [comment]
fixed in commit 5fbbe9c7479a7dc615b8d5630b9e1b2a6ce11b15
