### ISSUE TITLE
New phone formular should also accept truncated MAC addresses

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#80]
I use "arp -a" to find out the MAC address of new phones before I manually add them to GS.
However the output is a bit different and misses leading zeroes, for instance:

0:4:13:48:17:d3

The web form should also accept this and automatically add leading 0 where applicable.

**Comment by wintermeyer** [comment]
Done. 2e3bddd415f03aa15cd2759d7c18f64d5545ea80
