### ISSUE TITLE
Direct jump link to Snom web interface for admins

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#84]
Admins should have a link in the phone config details to directly jump to the phone's web interface including http user and password (not sure if it can be fully automatic with just a single click as one should avoid having the credentials in the URL like https://user:password@0.0.0.0 ...)

**Comment by wintermeyer** [comment]
Good thinking!

**Comment by jpawlowski** [comment]
e758cec9a842e75abe0a26312c4d7d3e8530b84a
