### ISSUE TITLE
Put GS5/config/initializers/secret_token.rb into DB

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#89]
Can we also put the secret token into the database?
I would take care of adapting the initial script to randomize it on first bootup.

**Comment by wintermeyer** [comment]
Good catch! I added it to GsParameter and created a migration. So now need for an inital script on your side. 
a742a9038210691169b407c2897a38ded8618f84

**Comment by jpawlowski** [comment]
are you sure this is still needed?
Doesn't "SecureRandom.hex(64)" generate an individual value during first database migration?

**Comment by wintermeyer** [comment]
Yes, and because it is stored in the database admins can upgrade their installation without a problem.

**Comment by jpawlowski** [comment]
I inteprete 'yes' as "yes, it's done during first migration and we don't need to update this value from the bootup script" ;-)

**Comment by wintermeyer** [comment]
Correct. ;-)
