### ISSUE TITLE
Version number should be in the footer of each page.

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#9]

**Comment by jpawlowski** [comment]
I suggest using the extended version number including the build information (or maybe as a mouseover).

Like in /etc/init.d/gdfdl-prompt you would get these information from file /etc/gdfdl_build which should just be added to the major version from gemeinschaft_parameters.rb

Afterwards the extended version number should look like

5.0.1234567890

This does not hinder us to do bugfix releases as we would just name GEMEINSCHAFT_VERSION = '5.0.1' where the build information is simply added.
