### ISSUE TITLE
Static IP 192.168.0.150 in GsParameters table

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#96]
There are still a few parameters in GsParameters with static IP address 192.168.0.150 set.
Update of these settings is currently not done during system bootup as it was with static files before (only HOMEBASE_IP_ADDRESS will be updated). Instead these settings should be generated dynamically by the GS5 code.

**Comment by wintermeyer** [comment]
I can't find them in my development environment. Which parameters should I check? 

```
~/Development/GS5 (develop ✔) ᐅ rails c
Loading development environment (Rails 3.2.2)
1.9.3-p286 :001 > GsParameter.where(:value => '192.168.0.150')
  GsParameter Load (0.5ms)  SELECT "gs_parameters".* FROM "gs_parameters" WHERE "gs_parameters"."value" = '192.168.0.150'
 => [] 
1.9.3-p286 :002 > 
```

**Comment by jpawlowski** [comment]
the value does only include 192.168.0.150 together with other things (URL definitions).

look for:
phone_book_entry_image_url
ringtone_url
user_image_url

**Comment by wintermeyer** [comment]
Fixed.

@span Please double check the values in https://github.com/amooma/GS5/blob/9567f239586f253002dea0ed654b7bd18a15e572/app/controllers/gemeinschaft_setups_controller.rb#L44-L47
