### ISSUE TITLE
Caching: SIP hotdeskable and CLIP-noscreening

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#97]
SIP account views miss values for setting hotdeskable and clip-noscreening.
Most likely another caching issue

**Comment by wintermeyer** [comment]
Please provide the URLs.

**Comment by jpawlowski** [comment]
e.g.

/tenants/2/phones/new
/tenants/2/sip_accounts/new
/users/1/phones/new

/users/1/sip_accounts/new is fine though.

**Comment by wintermeyer** [comment]
It's not a bug but a feature. Please read the message which is displayed over the form.

**Comment by jpawlowski** [comment]
I don't see any text saying "hotdeskable is not possible here" or so...
where should I look at?

![Screen Shot 2013-01-15 at 19 22 39](https://f.cloud.github.com/assets/75446/68721/c627d310-5f40-11e2-87df-e47adf10a497.png)
![Screen Shot 2013-01-15 at 19 23 03](https://f.cloud.github.com/assets/75446/68723/ca9e63be-5f40-11e2-9238-3196e87e33c0.png)
![Screen Shot 2013-01-15 at 19 23 14](https://f.cloud.github.com/assets/75446/68724/ce26aa82-5f40-11e2-9673-113c0c64b4bd.png)

**Comment by wintermeyer** [comment]
@spag deactivated the possibility to make a tenant's phone hotdeskable by c24bd3a8212e85894b2f7c26e190fe5e89fbaaf2

@spag Can you add a comment which describes the reason?
