### ISSUE TITLE
Use version from Git tagging instead of static value from DB

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#98]
Version control should be dropped from the database (delete GEMEINSCHAFT_VERSION).
Instead the installed version should be dynamically loaded by using Git command `git tag -l` which shows all tags:

5.0
5.0.1
5.0.2

The last line would be the actual version and could be used as value for GEMEINSCHAFT_VERSION.

However, the addition "-nightly-build" for development builds should be dropped completely.
Instead the tagged-version should be adjusted as followed:
1. In case `git rev-parse --abbrev-ref HEAD` outputs `HEAD` _or_ `master` the version number is already complete (this is the case for production versions).
2. In case `git rev-parse --abbrev-ref HEAD` has different output the version numer is recalculated as followed:
   - the very last number after the second period is aggregated by 1 (e.g. 5.0.2 -> 5.0.3)
   - the text "-preview" is added (e.g. 5.0.3 -> 5.0.3-preview)

It doesn't matter if there will actually be a version `5.0.3` as shown in the example. What counts is that this shows a preview status for the next version after the current release.
The naming "nightly-build" is a bit imprecise as there are more than one development builds. Also it's not correct to have a new build of an already released version showing up.

I will implement the same behavior in GBE.

**Comment by jpawlowski** [comment]
GBE implementation done with commit https://github.com/amooma/GBE/commit/c4108a5ed6c23b33cb05516f271a4a07435ec040

**Comment by jpawlowski** [comment]
Also to avoid too big version jumps we should agree to always set the minor version in the tags so that it's the minor version getting increased. Otherwise we would have a preview version "5.2-preview" right after 5.1 release which is likely not what we want.

Therefore I already corrected the tags in the GS5 repo, we now have:

5.0.0
5.0.1
5.0.2

Next one would be 5.1.0 then ;-)

**Comment by jpawlowski** [comment]
with commit https://github.com/amooma/GBE/commit/897fdbe1522f65353131468235bde4110dd9731c you should be able to use ENV['GS_VERSION'] and all other GS_\* environment variables directly

**Comment by wintermeyer** [comment]
I'm quite happy about this. :-)

What version number does the nightly build from develop get?

**Comment by jpawlowski** [comment]
As our current production version is tagged with 5.0.2, all develop builds (including the nightly build which is simply another develop build run at a specific time) currently get 5.0.3-preview.
(5.0.2 + 0.0.1 + -preview)

**Comment by jpawlowski** [comment]
Instead of using static "-preview" we might be able to just use the branch name.
I could take care of re-naming the branch from "develop" to "nightly-build" for this special build. that way we are totally flexible and if we would ever have a feature-branch or any customer specific branch this name would also show up in the version

**Comment by wintermeyer** [comment]
I doesn't have to be named "nightly-build". Maybe "develop" is the better name. Your call.

**Comment by jpawlowski** [comment]
\o/
Then I would use the direct branch name for now. ;-)
